### ISSUE TITLE
hyStrath on Archer2

### ISSUE THREAD

**Issue by dylewiczk** [vincentcasseau/hyStrath#100]
Hi,

I tried installing hyStrath on Archer2 (dsmcFoam+ specifically) but I had issues when using OpenFOAM v1906. At the same time, Archer2 support informed me that _OpenFOAM-v1706 (June 2017) is a very old version of the software, this is version 5 and relies on an outdated version of the GCC compiler which we are unable to support on ARCHER2_. I was wondering if the development team knows any work-arounds that would allow installing the dsmcFoam+ with newer versions of OF?

Many thanks!

Error traceback for OpenFOAM v1906:
```
> ./install.sh
-----  INSTALLATION  -----
1 - CFD module
2 - DSMC module
3 - Hybrid PIC-DSMC module
4 - All modules

-----  SYNCHRONISATION  -----
11 - CFD module
12 - DSMC module
13 - Hybrid PIC-DSMC module
14 - All modules

Enter choice: 2
[                    ]   4% installing DSMC module./install.sh: line 77: 104602 Terminated              progress_bar $sleep_period "installing DSMC module"
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC
```
logInstall-DSMC attached below.
[logInstall-DSMC.txt](https://github.com/vincentcasseau/hyStrath/files/8701787/logInstall-DSMC.txt)

**Comment by vincentcasseau** [comment]
Hi Kamil,

There are no workarounds for dsmcFoam+, the particle tracking method changed in subsequent versions of OpenFOAM.
The only solution is to upgrade the code to a later version. This has already been discussed in one previous Issue but it would be very time-consuming.

Thanks,
Vincent

**Comment by dylewiczk** [comment]
Hi Vincent,

Many thanks for your answer. Much appreciated!
