### ISSUE TITLE
some errors from tutorial

### ISSUE THREAD

**Issue by pixingcai** [vincentcasseau/hyStrath#102]
Hi  , Dr. Vincentcasseau , when I cd to hyStrath/hy2Foam/NASA_MSL_forebody/NASA_MSL_forebody_R, 
and execute : ./Allclean   ---->   ./Allrun,           some errors are reported and the case aborted,as following:
Illegal dictionary entry or environment variable name "Y_NO" Valid dictionary entries are 13(..............................)

Can you help me to figure it out ? thanks a lot

**Comment by vincentcasseau** [comment]
Hello,

Good catch, thanks for reporting it.
It's fixed in commit 87d00701.

Regards,
Vincent

**Comment by pixingcai** [comment]
> Hello,
> 
> Good catch, thanks for reporting it. It's fixed in commit [87d0070](https://github.com/vincentcasseau/hyStrath/commit/87d007015e6edf4037146e5808e83478749c6b01).
> 
> Regards, Vincent

Thanks 
It does work
