### ISSUE TITLE
More user manual or tutorial for PdFoam are needed

### ISSUE THREAD

**Issue by pixingcai** [vincentcasseau/hyStrath#103]
Dr. Vincentcasseau
         Can the PdFoam for rarefied plasma flow be further developed with external  electromagnetic field module, for  analysing the interaction between external  electromagnetic field and hypersonic plasma flow.  It would be really useful .
           Further, Would you please update more user manual or tutorial for the PdFoam solver ,IN DETAIL. It is really helpful for me.

Best wishes.

**Comment by vincentcasseau** [comment]
Hi,
The manual may come in due time.
I am afraid we don't take requests for further developments in the Issues.
Thanks,
Vincent

**Comment by s42001771** [comment]
Hey Vince,

Chiming in here. There are some NZ folks looking to add an EM solver to
pdFOAM. Did you want me to link you up with them?

Cheers,
Chris

**Comment by vincentcasseau** [comment]
Hi Chris,
If they wish to contribute, they are more than welcome.
What I can't do is to actively participate in the solver development. 
Cheers,
Vincent
