### ISSUE TITLE
Doubt Regarding hy2Foam Installation

### ISSUE THREAD

**Issue by ayush-s9** [vincentcasseau/hyStrath#106]
Hello,

I am trying to install hy2Foam on CentOS 7. I installed and compiled OpenFOAM-v1706 using the default CentOS compiler gcc 4.8.5, and OpenFOAM was working without any problems. I upgraded to gcc7.3.1 in order to get hy2Foam compiled but am facing linking issues. There are a lot of undefined references to certain libraries before the compilation terminates. Is it due to the fact that I compiled OpenFOAM using an older gcc version, or should I check for other problems?
Any help would be much appreciated. 

Regards,
Ayush Sharma.

**Comment by vincentcasseau** [comment]
Hi Ayush,
hyStrath has not been tested on CentOS and I have no experience installing OpenFOAM on CentOS.
Did you use the same OpenFOAM-v1706 source files as in Ubuntu?
Could you please send me the log file?
Thanks,
Vincent

**Comment by ayush-s9** [comment]
Hi Vincent,
Yes, I used the same source files as Ubuntu. 
I was following this tutorial for the installation(https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-v1712/CentOS_SL_RHEL), except for the step where I used the v1706 files.
Please find attached the log file for reference.
Thank you,
Ayush.
[logInstall-CFD.txt](https://github.com/vincentcasseau/hyStrath/files/9070225/logInstall-CFD.txt)

**Comment by vincentcasseau** [comment]
It's not finding some libraries that should have been compiled during the installation of OpenFOAM v1706:
```
/usr/bin/ld: warning: libOpenFOAM.so, needed by /home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Debug/lib/libfiniteVolume.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libPstream.so, needed by /home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Debug/lib/libfiniteVolume.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libsurfMesh.so, needed by /home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Debug/lib/libfiniteVolume.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libthermophysicalProperties.so, needed by /home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Debug/lib/libfluidThermophysicalModels.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libsolidSpecie.so, needed by /home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Debug/lib/libsolidThermo.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libfileFormats.so, needed by /home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Debug/lib/libmeshTools.so, not found (try using -rpath or -rpath-link)
```

Could you please search if `libOpenFOAM.so` exists on your disk. If so, I bet the path `/usr/bin/ld` is wrong and you would need to change that in `~/OpenFOAM/OpenFOAM-v1706/etc/bashrc` (that is compare the location of `libOpenFOAM.so` with what you had on Ubuntu and make sure they are the same).
If not, run `./Allwmake` again in `~/OpenFOAM/OpenFOAM-v1706/`, you should see some errors.

**Comment by ayush-s9** [comment]
During the OpenFOAM installation, I had to change the WM_COMPILE_OPTION to debug, since it was not working with the default option. Since I tried to compile it both ways, in the $WM_PROJECT_DIR/platforms directory, I have multiple directories in the platforms directory, but the path to the correct one(which compiled properly) was added in the ~/.bashrc.
As for the test for finding libOpenFOAM.so, it was there in the directory platforms/linux64GccDPInt32Debug/ where the remaining desired files are also present.

Just now, the hy2Foam compilation proceeded to 99% but was stuck there for around 5 minutes, but the log file was not updated from the previous compilation.

**Comment by ayush-s9** [comment]
Still, I removed the build directory and emptied the platforms directory in order to try to run ./Allwmake again.

Thanks,
Ayush.

**Comment by vincentcasseau** [comment]
> I had to change the WM_COMPILE_OPTION to debug, since it was not working with the default option.

Is this is a known limitation on CentOS? Computations will be slower...

Could you please attach
- `~/OpenFOAM/OpenFOAM-v1706/etc/bashrc`
- the logfile given by the Allwmake in `~/OpenFOAM/OpenFOAM-v1706`

and give here the output of:
```sh
echo $WM_PROJECT_DIR
echo $WM_PROJECT_USER_DIR
```
Thanks

**Comment by vincentcasseau** [comment]
If you look at the first warning:
```sh
warning: libOpenFOAM.so [...] not found
/home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Opt/lib/libfiniteVolume.so
```
it says `libfiniteVolume.so` isn't found in `/home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Opt/lib/`.
Can you confirm using `ls`.

**Comment by ayush-s9** [comment]
I am attaching a picture of the lib directory(all the files it mentions that it is unable to find are actually there):
![lib](https://user-images.githubusercontent.com/85876808/177992929-35cc4fae-3073-4921-b158-8aef4b1848c4.png)

**Comment by ayush-s9** [comment]
I even compared the files with the ones on my Ubuntu device, and they were the same. There the problem of undefined references was not arising.
I am doing the installation from root, where the environment variables are not accessible.
Can that be the culprit here? Do I have to have access to them during the compilation of hy2Foam or will the compiler work in the way the OpenFOAM compiler worked? 
But the OpenFOAM version was also compiled from root, and it seemed to work there.

Thanks,
Ayush

**Comment by vincentcasseau** [comment]
You shouln't be using root to install OpenFOAM nor hyStrath.

I may have misinterpreted the path in my last message, in full it gives
```
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: warning: libOpenFOAM.so,
needed by /home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Opt/lib/libcompressibleTransportModels.so,
not found (try using -rpath or -rpath-link)
```
As you said, `libOpenFOAM.so` is in `/home/pa2/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Opt/lib/`, not in
`/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld`.

I would delete `OpenFOAM/OpenFOAM-v1706` entirely and reinstall it as a user at this point.

**Comment by ayush-s9** [comment]
Thanks, I didn't notice this.
I will recompile OpenFOAM from the user and see if it works.

**Comment by ayush-s9** [comment]
Hi Vincent,

Thanks a lot for your help. I was able to compile hyStrath once I recompiled OpenFOAM from scratch. I ran the heatBath case and the test results were successful.

Thanks again,
Regards,
Ayush.
