### ISSUE TITLE
What is the equation for alphave in Smoluchowski temperature jump BC

### ISSUE THREAD

**Issue by richardliuss** [vincentcasseau/hyStrath#108]
Hi everybody,
    I am currently working on the Smoluchowski temperature jump BC, nonEqSmoluchowskiJumpTvMix to be specofic. However, what puzzled me is the equation in the code did not express in the same way as Dr. Daniel Espinoza did in his PhD thesis. I really wondered the expression for the variable palpha. 
    I already found the palpha is actually the value of alphave, but I did not found the defination expression of alphave. 
    Thank you so much!

    scalarField C2
    (
        pmfp*2.0*pgamma/(pgamma + 1.0)/(pmu/palpha)
      * (2.0 - accommodationCoeff_)/accommodationCoeff_
    );

    valueFraction() = (1.0/(1.0 + patch().deltaCoeffs()*C2));
    refValue() = Twall_;
    refGrad() = 0.0;

Many Thanks!
Richard

**Comment by vincentcasseau** [comment]
Hi Richard,
palphave is the value of the mixture (for `nonEqSmoluchowskiJumpTvMix`) vibro-electronic thermal diffusivity at the boundary patch (thus, _p_ for patch).
 
The definition of the **species** vibro-electronic thermal conductivity is given in any class present in this folder:
[src/thermophysicalModels/strath/strathSpecie/transport/speciesTransport/](https://github.com/vincentcasseau/hyStrath/tree/master/src/thermophysicalModels/strath/strathSpecie/transport/speciesTransport)
The relation between **modal species** thermal conductivity and **modal species** thermal diffusivity is given in this class:
[reactionThermo/mixtures/Specie2Mixture/Specie2Mixture.C](https://github.com/vincentcasseau/hyStrath/blob/master/src/thermophysicalModels/strath/strathReactionThermo/reactionThermo/mixtures/Specie2Mixture/Specie2Mixture.C#L929-L941)

Wilke's mixing rule to derive the **mixture modal** thermal diffusivities is given here:
https://github.com/vincentcasseau/hyStrath/blob/master/src/thermophysicalModels/strath/strathSpecie/transport/mixingRules/Wilke/WilkeMR.C

Thanks,
Vincent

**Comment by richardliuss** [comment]
Greetings Dr. Vincent,
     Thank you for your reply. That helped me alot.
     As I went through the files you mentioned, it is very interesting to find that in the [SutherlandEuckenTransportl.H](https://github.com/vincentcasseau/hyStrath/blob/master/src/thermophysicalModels/strath/strathSpecie/transport/speciesTransport/SutherlandEucken/SutherlandEuckenTransportI.H) Line 177 heat conducitvity of translational-rotational mode is defined as followed.
For N2, the corresponding Prandtl number of translational-rotational mode (Pr_tr) is usually taken as a value between 0.71-0.75. However, through the code, the Pr_tr is calculated to be around 0.69, which will result in a higher heat flux. I do wonder if there is an empirical formula employed in the code.

```
template<class Thermo>
inline Foam::scalar Foam::SutherlandEuckenTransport<Thermo>::kappatr
(
    const scalar p,
    const scalar Tt
) const
{
    scalar Cv = this->Cv_t(p, Tt);
    if (Cv > Foam::SMALL)
    {
        return mu(p, Tt)*Cv*(1.32 + 1.77*this->R()/Cv);
    }
    else
    {
        return 0.0;
    }
}
```
Best regards,
Richard

**Comment by vincentcasseau** [comment]
> However, through the code, the Pr_tr is calculated to be around 0.69

At what temperature?
This formula can be found here in OF-dev: https://github.com/OpenFOAM/OpenFOAM-dev/blob/master/src/thermophysicalModels/specie/transport/sutherland/sutherlandTransportI.H#L128-L137

**Comment by richardliuss** [comment]
Hi Dr.Vincent,
Assuming the gas is N2 at 300K, R=296.7 as a constant, Cv=5/2*R and Cp=7/2*R. 
Take everything into the formula (kappa=mu(p, Tt)*Cv*(1.32 + 1.77*this->R()/Cv)).
It turned out to be kappa=mu*Cp/Pr=5.07*mu*R=1.44857*mu*7/2*R=mu*Cp/0.69.
Thanks,
Richard
