### ISSUE TITLE
Stages of dsmcFoam+ simulation

### ISSUE THREAD

**Issue by dylewiczk** [vincentcasseau/hyStrath#109]
Hello,
I am running a Couette flow tutorial with dsmcFoam+ in parallel on 20 cores and I do not fully understand code's behaviour. What are the ''stages'' of the computation? At the end of every stage the code terminates, reconstructs the solution from processors and restarts. I do not understand why this is happening. I attach examples of the outputs informing me about different stages below where number of iterations and execution time in fact indicate that these are two different simulations. I was hoping that someone on this forum could explain or point me to the resources that would explain this.

```
Time = 0.001

    Collisions                      = 11724

    Number of DSMC particles        = 94983
    Number of stuck particles       = 0
    Number of free particles        = 94983
    Average linear kinetic energy   = 5.210469518e-20
    Average rotational energy       = 3.405885424e-20
    Average vibrational energy      = 1.706554625e-20
    Average electronic energy       = 0
    Total energy                    = 0.004211998546

Stage 1.0  ExecutionTime = 1.91 s  ClockTime = 2 s  Iteration 100 (0.02 s)
```

```
Time = 1.001

    Collisions                      = 11640

    Number of DSMC particles        = 94983
    Number of stuck particles       = 0
    Number of free particles        = 94983
    Average linear kinetic energy   = 5.207844707e-20
    Average rotational energy       = 3.433012343e-20
    Average vibrational energy      = 1.731586089e-20
    Average electronic energy       = 0
    Total energy                    = 0.004232209451

Stage 2.0  ExecutionTime = 1.83 s  ClockTime = 2 s  Iteration 100 (0.02 s)
```
On the side note, is there any documentation that explains the averaging process in dsmcFoam+ in detail? In my simulations I am interested in the unsteady behaviour of the flow so I need to understand the averaging process to get meaningful temporally resolved flow fields.  

Thanks!

**Comment by vincentcasseau** [comment]
Hi Kamil,

- Stages: You must have allowed load balancing somehow. This is explained here: https://hystrath.github.io/how-tos-dsmc-fleming/how-tos-dsmc-fleming-load-balancing/
Let me know if something is not clear in the doc, I will improve it.
- Averaging: I imagine you saw that: https://hystrath.github.io/how-tos-dsmc-fleming/how-tos-dsmc-fleming-sampling/#3-transient-simulations
The averaging process is very simple: microscopic quantities are cumulated over time in dedicated arrays, at write-time these values are divided by the current number of samples and the formulas given in Bird's book (2013 edition) are used to derive macroscopic quantities. If you are interested in the unsteady flow behaviour, you should reset these microscopic fields at each time using ```resetAtOutput on``` to obtain their instantaneous values. To reduce scatter, you could run multiple statistically-independent simulations and geometrically average the results at each write time.

Thanks

**Comment by dylewiczk** [comment]
Hi Vince,

Thanks for your answers and links. They explain a lot. 

In the meantime, I realised another question and I could not find the answer in the documentation. Is it possible to impose a numerical profile at the inlet (e.g. boundary layer or solution from a different simulation) in dsmcFoam+?

Thanks

**Comment by vincentcasseau** [comment]
Yes, using `dsmcFreeStreamInflowFieldPatch` and the boundaryT/boundaryU files.
See src/lagrangian/dsmc/boundaries/derived/generalBoundaries/dsmcFreeStreamInflowFieldPatch/dsmcFreeStreamInflowFieldPatch.C/H
