### ISSUE TITLE
Help using AMR

### ISSUE THREAD

**Issue by Peter1511ogluigi** [vincentcasseau/hyStrath#111]
Dear Sir

I am trying to use AMR in simulation concerning a blunt cone. 
I have followed the instructions described in [tutorial](https://hystrath.github.io/how-tos-cfd-fleming/how-tos-cfd-fleming-advanced/#5-adaptive-mesh-refinement) by adding the dynamicMeshDict to the constant folder. After I have done this, I use the command `hy2DyMFoam > log.hy2DyMFoam 2>&1 &` to run the desired calculation. When I do this, my terminal only gives the following feedback
![image](https://user-images.githubusercontent.com/47326008/183403403-9ac4f0b3-9de0-4efa-84da-e07afdebf5c7.png)

The mesh I am using, which has been created in gmsh, consists of 60x30 cells and looks like the following
![image](https://user-images.githubusercontent.com/47326008/183403890-0137927b-bba4-496a-bacd-1ef49a103dde.png)

Now, the simulations seems to run, giving results at the desired timesteps. However, when I check with paraview there is clearly no change in the structure of the mesh being used. 
The dynamicMeshDict I have used is given as 

![Screenshot from 2022-08-08 13-06-43](https://user-images.githubusercontent.com/47326008/183404699-e3260235-f8ff-40bb-8563-03648346068c.png)

I wish to use AMR in later calculations with more complex geometries, so help in using this method is greatly appreciated. 
Do you know why I cannot seem to get it to work?

/Peter

**Comment by Peter1511ogluigi** [comment]
Hi Vincent
Thanks for the quick reply
The idea behind this example was to get acquainted with the AMR method. Now, I will surely use a structured mesh if it is possible, however I think it would be nice to know how to use AMR. 
I have changed the dynamicMeshDict such that the refinement is dependent of the machGradient. The results acquired are as shown
![image](https://user-images.githubusercontent.com/47326008/183421420-d8fa2028-6d15-473e-82a9-454a147439cf.png)

When using AMR, should I not expect the resolution to increase in the high gradient areas?
(my refine values are: refineInterval  10000; lowerRefineLevel 1e3;  upperRefineLevel 1e5;)

**Comment by Peter1511ogluigi** [comment]
Thanks for the fast reply
I will take note of using AMR with care, but is at the time just interested in getting acquainted with the method. 
I have tried running with a refineinterval of 1 which gives me the following error
![image](https://user-images.githubusercontent.com/47326008/183582833-fa9ec44c-8e9e-4832-bd6b-32eab40b5421.png)

Do you know what the problem is? (my conditions are     refineInterval  1; field alphat; lowerRefineLevel 0.0001; upperRefineLevel 1; unrefineLevel 10; nBufferLayers   2; maxRefinement   3;maxCells        100000; )

**Comment by Peter1511ogluigi** [comment]
Hello Vincent
Thanks for the fast reply
I am trying to compare results using AMR with results from a very fine structured mesh, so it just to see the usefulness of AMR.
I have tried changing the refinement levels, and it seems to work so that is very nice. 

A problem I now face is that the refinement can only be done on a certain set of values. 
I wish to refine regions of high temperature therefore having refinement from 1000 K to 20000 K.
With the mesh I currently use (finer than shown on image above), I can refine in the region from 3000 K to 20000 K. 
Do you know why I cannot refine below 3000 K?

here is my dynamicMeshDict

![image](https://user-images.githubusercontent.com/47326008/183855744-efefcbb7-133e-4be5-bdc0-cd0ea63bf630.png)

**Comment by vincentcasseau** [comment]
Have you tried setting your `unrefineLevel` to a value lower than your freestream value? Maybe there is no room to accommodate 2 buffer layers between each level.
What if you use an even finer mesh in this area?

**Comment by Peter1511ogluigi** [comment]
I have tried changing the unrefineLevel but it does not seem to change anything. Have also tried to change the number of buffer layer with no luck whatsoever. When changing the mesh I achieved a larger domain of data to refine (coarse might only allow mesh refinement from 5000-15000 K while fine mesh allows refinement for 3000 - 20000 K)

I had hoped that AMR would allow a rather coarse mesh, which would be easy to generate, to be refined. However, as it looks so far, the mesh needs to be of pretty high quality before the AMR will take over.

**Comment by vincentcasseau** [comment]
Could you post a picture of the "fine mesh that allows refinement for 3000 - 20000 K" with the Tov solution overlaid.

**Comment by Peter1511ogluigi** [comment]
Here are some images. I have just realized that a "fine" mesh in this case is 60x70 cells.

![img1](https://user-images.githubusercontent.com/47326008/184082867-c8d4a268-f2ba-46f0-9c7c-d19b86baa061.png)
![img2](https://user-images.githubusercontent.com/47326008/184082870-87843d21-083c-425d-b6e0-edca95c1cf86.png)
![img3](https://user-images.githubusercontent.com/47326008/184082879-57d6e294-1dde-438c-824f-00c3079a421e.png)

**Comment by vincentcasseau** [comment]
I can't see why there is a the problem, the mesh is refined upstream the shock on the second picture.
Are there only cells of levels 0 & 1 in this domain?

**Comment by Peter1511ogluigi** [comment]
I agree that the mesh is refined as hoped, however I still wonder why it cannot refine below 3000 K. 
In this run I set the maxRefinement to be 1.

**Comment by Peter1511ogluigi** [comment]
![img4](https://user-images.githubusercontent.com/47326008/184088682-ac60ea97-57a5-444b-88d1-3adc361e97a6.png)

**Comment by vincentcasseau** [comment]
Please send me a zip of your case by email. Thanks

**Comment by vincentcasseau** [comment]
1. Visualise cell-center values, not the interpolated nodal solution;
2. When the mesh update is synchronised with the outputTime (constant Dt), and `lowerRefineLevel` is set to 2500, it works (all red cells are level 1 in the first picture);
3. If you further decrease `lowerRefineLevel`, it gets unstable because of the mesh choice (axisymmetric -> the first layer next to the revolution axis doesn't get refined: tets aren't dealt with by AMR) and because of the refinement criterion (the first few layers next to the cone won't get refined either).

All in all, no issues at all, just not the best case. You could aim to replicate the test cases shown in Daniel Espinoza's 2015 conference paper to experiment with AMR.

![Screenshot from 2022-08-11 10-45-48](https://user-images.githubusercontent.com/10944529/184096981-39b84847-0f8e-4b5c-9ccb-408ebec6eace.png)
![Screenshot from 2022-08-11 10-44-37](https://user-images.githubusercontent.com/10944529/184096934-48582eea-7196-4de5-b9f1-2785acacbcb6.png)
![Screenshot from 2022-08-11 10-45-15](https://user-images.githubusercontent.com/10944529/184096964-5df7e35e-afac-4e49-a488-2f903932bf21.png)

**Comment by Peter1511ogluigi** [comment]
Thank you very much, your help is much appreciated (as always)
I will try with the other test case instead

Den tor. 11. aug. 2022 kl. 10.58 skrev Vince ***@***.***>:
