### ISSUE TITLE
Introducing disturbance to macroproperties 

### ISSUE THREAD

**Issue by dylewiczk** [vincentcasseau/hyStrath#112]
Hi Vince,

what files does dsmcFoam+ read on the restart from the results folder? I want to introduce a disturbance (e.g. a sine wave) to macroproperties (pressure, temperature, velocities etc.) and then restart dsmcFoam+ and perform some analysis. 

I am wondering if I perturb `0.5/Ttra_Ar`, `0.5/U_Ar` and `0.5/p_Ar` and restart the simulation, will dsmcFoam+ read those files to initialise the restart (in other words will the perturbation have any effect on the restarted simulation) or does it only use microscopic properties in `0/lagrangian/dsmc`?

Thanks for your help,
Kamil

**Comment by vincentcasseau** [comment]
Hi Kamil,

You can't restart using macroscopic fields alone, this has not been implemented yet. The class `dsmcMeshFill` takes single input values for modal temperatures, velocity and number densities only, not fields.
When you restart a simulation, it uses <resultsFolder>/lagrangian/dsmc fields. Your perturbation script will need to edit these files.

Thanks,
Vincent

**Comment by dylewiczk** [comment]
Makes sense! Thanks again.
