### ISSUE TITLE
Mixed boundary conditions

### ISSUE THREAD

**Issue by alexandercushen** [vincentcasseau/hyStrath#113]
What is the syntax for using the "mixed" boundary conditions, for instance a wall patch which is diffuse or specular some fraction of the time?

**Comment by vincentcasseau** [comment]
Hi Alex, I added a section on the website:
https://hystrath.github.io/how-tos-dsmc-fleming/how-tos-dsmc-fleming-boundary-conditions/#33-diffuse-specular-wall
Thanks
