### ISSUE TITLE
Issue with installation in wsl

### ISSUE THREAD

**Issue by PrikMushi** [vincentcasseau/hyStrath#129]
Hi

I have OpenFoam v2012 installed in Ubuntu 22.04.2 LTS. I am not aware of any installation instruction specifically for wsl, so I followed as per the instrutions here https://hystrath.github.io/installation/, after installing OpenFoam.

I get this error when I try to install

-----  INSTALLATION  -----
1 - CFD module
2 - DSMC module
3 - Hybrid PIC-DSMC module
4 - All modules

-----  SYNCHRONISATION  -----
11 - CFD module
12 - DSMC module
13 - Hybrid PIC-DSMC module
14 - All modules

Enter choice: 2
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC

Any suggestions to fix the issue?

**Comment by timteichmann** [comment]
Hi,
As stated in the instructions

> 1. In Ubuntu **20.04 LTS (22.04 LTS isn’t supported yet)**, downgrade gcc and g++ to version 7

Naturally, the same applies to WSL Ubuntu, so you might try with version **20.04**. Also please note, that this is built on and compatible only with OpenFOAM v1706 not v2012. Regarding the installation on Ubuntu 20.04 you might also want to check:

- https://github.com/hystrath/hyStrath/issues/83
- https://www.cfd-online.com/Forums/openfoam-installation/203125-v1712-build-error.html#post798989

**Comment by PrikMushi** [comment]
Hi 

Thank you for your reply. 

What is the difference between the hyStrath method and the method mentioned here?
https://github.com/MicroNanoFlows/OpenFOAM-2.4.0-MNF/blob/master/doc/MicroNanoFlows/MNF_Repository_Install.pdf

Also, I still get the same error.

I made a fresh installation of Ubuntu 20.04 LTS, then downgraded gcc and g++ version to 7. After that OpenFoam v1706 was installed, and it works. Then, I cloned the hyStrath Github repository. But when I try to install using the ./install.sh NUMPROCS 2>/dev/null command, I get this error

----- INSTALLATION -----
1 - CFD module
2 - DSMC module
3 - Hybrid PIC-DSMC module
4 - All modules

----- SYNCHRONISATION -----
11 - CFD module
12 - DSMC module
13 - Hybrid PIC-DSMC module
14 - All modules

Enter choice: 2
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC

Did I miss out something?

**Comment by PrikMushi** [comment]
Also, I still get the same error.

I made a fresh installation of Ubunut 20.04 LTS, then downgraded gcc and g++ version to 7. After that OpenFoam v1706 was installed, and it works. Then, I cloned the hyStrath Github repository. But when I try to install using the  ./install.sh NUMPROCS 2>/dev/null command, I get this error

-----  INSTALLATION  -----
1 - CFD module
2 - DSMC module
3 - Hybrid PIC-DSMC module
4 - All modules

-----  SYNCHRONISATION  -----
11 - CFD module
12 - DSMC module
13 - Hybrid PIC-DSMC module
14 - All modules

Enter choice: 2
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC

Did I miss out something?

**Comment by timteichmann** [comment]
Hi,
Just to make sure: if you say you ran ` ./install.sh NUMPROCS 2>/dev/null`, you mean you ran the command but with a number instead of `NUMPROCS`? And what is the content of the log file mentioned after the `FAIL`?

**Comment by PrikMushi** [comment]
Hi

I simply copy pasted the command ./install.sh NUMPROCS 2>/dev/null; by number, I suppose by default it is 2.

The contents of logInstall-DSMC are attached in the file below
[logInstall-DSMC.txt](https://github.com/hystrath/hyStrath/files/10870846/logInstall-DSMC.txt)

**Comment by PrikMushi** [comment]
Okay, I could install it now. Thank you!
