### ISSUE TITLE
Issue during dsmcFoam+ initialization

### ISSUE THREAD

**Issue by PrikMushi** [vincentcasseau/hyStrath#130]
Hi

I am new to dsmcFOAM+, but have used dsmcFOAM before. I tried running the tutorial case "supersonicFlatPlate", just to check. 
I believe the procedure to intiate the tutorial is same as dsmcFOAM: blockMesh -> dsmcInitialise -> dsmcFoam

Please correct me if I am wrong.

blockMesh works, but when I type in dsmcInitialise, i get this error. Any suggestions as to how I can fix this? 

![image](https://user-images.githubusercontent.com/126686965/222439790-5b39d7be-861e-4930-8cd2-350a8ebe51b2.png)

**Comment by timteichmann** [comment]
Please check the [Allrun](https://github.com/hystrath/hyStrath/blob/master/run/hyStrath/dsmcFoam%2B/supersonicFlatPlate/Allrun) file in the case. This will pretty much tell you the expected order of things (if you want to do them manually step by step). Your issue might be related to the fact that the commands are called `dsmcInitialise+` and `dsmcFoam+`.
