### ISSUE TITLE
hy2Foam post-processing error with openFoam routines

### ISSUE THREAD

**Issue by astrogator11** [vincentcasseau/hyStrath#14]
Trying to run the hy2Foam bluntedCone and cylinderReacting cases. Running it on Windows using the Windows Subsystem for Linux with Ubuntu. 

I modified the Allrun scripts decompose and run on multiple cores. But I always end up with an error on the next postprocess step.

FOAM throws an error it can't find wallHeatFlux or wallShearStress, however, it appears to have been installed correctly because I can call those functions from my terminal.

> // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
> Create time
> 
> Create mesh for time = 0
> 
> --> FOAM Warning :
>     From function bool Foam::functionObjectList::read()
>     in file db/functionObjects/functionObjectList/functionObjectList.C at line 777
>     Caught FatalError
> --> FOAM FATAL ERROR:
> Unable to find the wallHeatFlux
> 
>     From function Foam::functionObjects::StantonNo::StantonNo(const Foam::word&, const Foam::Time&, const Foam::dictionary&)
>     in file StantonNo/StantonNo.C at line 121.
> 
> --> FOAM Warning :
>     From function bool Foam::functionObjectList::read()
>     in file db/functionObjects/functionObjectList/functionObjectList.C at line 777
>     Caught FatalError
> --> FOAM FATAL ERROR:
> Unable to find the wallShearStress
> 
>     From function Foam::functionObjects::frictionCoefficient::frictionCoefficient(const Foam::word&, const Foam::Time&, const Foam::dictionary&)
>     in file frictionCoefficient/frictionCoefficient.C at line 121.
> 
> Time = 0
> Creating reaction model
> 
> Selecting hTC model laminar2<rho2ChemistryHTC>
> Selecting chemistry type
> {
>     chemistrySolver Euler2Implicit;
>     chemistryThermo rho2;
> }
> 
> Selecting thermodynamics package
> {
>     type            heRho2Thermo;
>     mixture         reacting2Mixture;
>     transport       BlottnerEucken;
>     thermo          decoupledEnergyModes;
>     energy          sensible2InternalEnergy;
>     equationOfState perfect2Gas;
>     specie          advancedSpecie;
> }
> 
> Selecting chemistry2Reader foam2ChemistryReader
> chemistry2Model: Number of species = 2 and reactions = 2
>     using integrated reaction rate
> 
> Reading thermophysical properties
> 
> Reading field U
> 
> Creating turbulence model
> 
> Selecting turbulence model type laminar
> Selecting laminar stress model Stokes
> 
> Loading the transport mixing rule:      Wilke
> 
> Loading the rarefaction parameters library
> 
> Loading the multispecies transport model:       Fick
> 
> Loading the V-T relaxation time model:  LandauTellerVT
> 
> pressureCoefficient pressureCoefficient write:
>     writing field pressureCoefficient
>     patch cylinder Cp : min = 0.00357142, max = 0.00357142, average = 0.00357142
> 
> End
>

**Comment by vincentcasseau** [comment]
1) wallHeatFlux and wallShearStress are fields printed in the results folders, not apps.
You are launching **and** stopping your simulation at t=0. wallHeatFlux and wallShearStress are not input fields, therefore it will crash. You need to advance your simulation in time first.

2)  Careful, the reacting cylinder case is not a straight-forward tutorial - it's more of an exercice: https://github.com/vincentcasseau/hyStrath/issues/1#issuecomment-324940113

**Comment by astrogator11** [comment]
Thanks for the reply, Dr. Casseau! Sorry, I'm terribly new with all of this. 

If I didn't edit any of the other files, if I'm reading the controlDict correctly, shouldn't the simulation be running from 0s to 0.0002s as the default in the tutorial for the bluntedCone?

**Comment by astrogator11** [comment]
I do see in the log file that immediately upon running hy2Foam, there are repeated warnings of this variety. Could that be part of the failure to continue the simulation past time 0?

> Create time
> 
> Create mesh for time = 0
> 
> --> FOAM Warning :
>     From function virtual void Foam::wedgePolyPatch::calcGeometry(Foam::PstreamBuffers&)
>     in file meshes/polyMesh/polyPatches/constraint/wedge/wedgePolyPatch.C at line 70
>     Wedge patch 'rWedge' is not planar.
> At local face at (0.0116936 0.0048636 0.000169841) the normal (-2.13284e-08 -0.0348995 0.999391) differs from the average no
> rmal (-4.5879e-12 -0.0348995 0.999391) by 1.09378e-15
> Either correct the patch or split it into planar parts
> --> FOAM Warning :
>     From function virtual void Foam::wedgePolyPatch::calcGeometry(Foam::PstreamBuffers&)
>     in file meshes/polyMesh/polyPatches/constraint/wedge/wedgePolyPatch.C at line 70
>     Wedge patch 'rWedge' is not planar.
> At local face at (0.0120766 0.00515887 0.000180152) the normal (1.9366e-08 -0.0348995 0.999391) differs from the average nor
> mal (-4.5879e-12 -0.0348995 0.999391) by 1.03783e-15
> Either correct the patch or split it into planar parts
> --> FOAM Warning :
>     From function virtual void Foam::wedgePolyPatch::calcGeometry(Foam::PstreamBuffers&)
>     in file meshes/polyMesh/polyPatches/constraint/wedge/wedgePolyPatch.C at line 70
>     Wedge patch 'rWedge' is not planar.
> At local face at (0.0106252 0.00367889 0.00012847) the normal (2.7589e-08 -0.0348995 0.999391) differs from the average norm
> al (-4.5879e-12 -0.0348995 0.999391) by 1.13565e-15
> Either correct the patch or split it into planar parts

**Comment by vincentcasseau** [comment]
Actually, I thought your logfile was for the simulation logfile but it is not. Are the simus still running?
You can remove the 0/ folder from the list of time folders to be considered by the post processing utilities by adding the --noZero option to the command line.
Yes, and if you don't want to bother re-running from scratch, cc the backup-0.0002 folder to 0.0002 and run until you think it is appropriate.

**Comment by vincentcasseau** [comment]
The repeated warnings are coming from the use of makeAxialMesh (by Bernhard Gschaider:  http://openfoamwiki.net/index.php/Contrib/MakeAxialMesh) while creating the mesh. They can be disregarded.

**Comment by purewi** [comment]
@astrogator11 I aslo met the same problem. Could you tell me how to deal with it? Many thanks!
