### ISSUE TITLE
Unable to instal hy2foam

### ISSUE THREAD

**Issue by Tomjugj** [vincentcasseau/hyStrath#144]
I am using Ubuntu 20.04, and OpenFOAM-v1706 has been installed successfully. But I am unable to install hy2Foam, a message "FAIL: check logInstall-CFD" was coming. The logInstall-CFD file is as follows:

[logInstall-CFD.txt](https://github.com/hystrath/hyStrath/files/12047035/logInstall-CFD.txt)

i saw a line read: unknown option: '-jNUMPROCS'
Can anybody help me out?

**Comment by timteichmann** [comment]
As explained in the installation guide `NUMPROCS` is a placeholder that you have to replace with the number of cores you want to use in parallel for compilation, e.g. `-j8` to compile on 8 threads in parallel.

**Comment by Tomjugj** [comment]
Thank you so much! 
previously, i copied the command from the tutorial to the terminal: `./install.sh NUMPROCS 2>/dev/null` and failed.
as you suggested, i tried: `./install.sh 2>/dev/null` and it worked!
I will test a few cases to see if everything is ok.

**Comment by Tomjugj** [comment]
The zeo-dimensional case: 'Adiabatic heat bath' seems to be ok (./Alltest and it showed 'SUCCESS'), but when i ran the case 'Blunted cone', there are FOAM warnings like:
![image](https://github.com/hystrath/hyStrath/assets/139533265/baa0a638-0a24-4107-970a-bd5e33b5a3f9)
and :
![image](https://github.com/hystrath/hyStrath/assets/139533265/217c3df3-62ec-4171-ad44-c22dc743129e)

I did not modify the files, does anyone have any suggestion?
