### ISSUE TITLE
Missing boundary conditions pdFoam

### ISSUE THREAD

**Issue by craigwhite87** [vincentcasseau/hyStrath#20]
The 2d sheath tutorial for pdFoam requires a pdReflectiveParticleMembranePatch class. This is not included in the repository source code, so the tutorial cannot be run.

**Comment by s42001771** [comment]
Hi Craig, looks like you're right. I'll push up the boundary class. Feel free to let me know if you run into any other problems with pdFOAM or have recommendations for additional tutorials.

**Comment by s42001771** [comment]
Alternatively, @vincentcasseau, did you remove the pdReflectiveParticleMembranePatch to avoid code repetition since it's essentially the same as dsmcReflectiveParticleMembranePatch. I wonder if it's worth opening a job to abstract shared pic and dsmc BCs at some point.

**Comment by s42001771** [comment]
Ok, I've added the pdReflectiveParticleMembranePatch and updated the 2D_sheath examples to include both a boltzmann electron fluid and a fully kinetic charging example. Can you let me know if they work for you now and I'll close this issue.

As a side note, you can run the 2D_sheath cases without the pdReflectiveParticleMembranePatch - it's a cyclicBC that OF can also recognise and handle natively (see the FullyKineticCharging case). So I might remove and the BC and update the examples down the line unless there is a need for it.

**Comment by vincentcasseau** [comment]
Hi Chris,
You fixed the bug, that works for me. 
When I look at the Make/files of lagrangian/pic/, I can see that I had wished to re-use some of the DSMC capabilities. I remember setting this aside because of a lack of time - conflicts need to be resolved.
    /*-I$(WM_PROJECT_USER_DIR)/src/lagrangian/dsmc/lnInclude \*/
    /*-I$(LIB_SRC)/lagrangian/intermediate/lnInclude*/
But eventually, it would be ideal if the pic-dsmc solver could benefit from the latest improvements made in the dsmc lib.
