### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by Coding4ever4CFD** [vincentcasseau/hyStrath#26]
Hi Vincent, 

Thank you for sharing your great work. I'm a new user and having difficulties installing hyStrath on an ubuntu device (18:04). An error occurs in the followings and I'm not clear on the reason. Thank you very much in advance.

Kind regards,

"~/hyStrath/src/thermophysicalModels/strath/strathChemistryModel/functionObjects/specieReactionRates/specieReactionRates.C.

It states:
**....**
functionObjects/specieReactionRates/specieReactionRates.C:155:5: warning: there are no arguments to ‘file’ that depend on a template parameter, so a declaration of ‘file’ must be available [-fpermissive]
     file() << nl << endl;
     ^~~~
functionObjects/specieReactionRates/specieReactionRates.C: In instantiation of ‘Foam::functionObjects::specieReactionRates<ChemistryModelType>::specieReactionRates(const Foam::word&, const Foam::Time&, const Foam::dictionary&) [with ChemistryModelType = Foam::rho2ChemistryModel]’:
/opt/openfoam7/src/OpenFOAM/lnInclude/functionObject.H:164:9:   required from ‘static Foam::autoPtr<Foam::functionObject> Foam::functionObject::adddictionaryConstructorToTable<functionObjectType>::New(const Foam::word&, const Foam::Time&, const Foam::dictionary&) [with functionObjectType = Foam::functionObjects::specieReactionRates<Foam::rho2ChemistryModel>]’
/opt/openfoam7/src/OpenFOAM/lnInclude/functionObject.H:164:9:   required from ‘Foam::functionObject::adddictionaryConstructorToTable<functionObjectType>::adddictionaryConstructorToTable(const Foam::word&) [with functionObjectType = Foam::functionObjects::specieReactionRates<Foam::rho2ChemistryModel>]’
functionObjects/specieReactionRates/specieReactionRates.C:178:5:   required from here

functionObjects/specieReactionRates/specieReactionRates.C:79:5: **error: no** matching function for call to ‘Foam::functionObjects::writeFile::writeFile(const Foam::objectRegistry&, const Foam::word&, const Foam::word&, const Foam::dictionary&)’
     )
     ^
In file included from /opt/openfoam7/src/finiteVolume/lnInclude/volRegion.H:70:0,
                 from functionObjects/specieReactionRates/specieReactionRates.H:48,
                 from functionObjects/specieReactionRates/specieReactionRates.C:26:
/opt/openfoam7/src/OpenFOAM/lnInclude/writeFile.H:82:9: note: candidate: Foam::functionObjects::writeFile::writeFile(const Foam::objectRegistry&, const Foam::word&)
         writeFile
         ^~~~~~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/writeFile.H:82:9: note:   candidate expects 2 arguments, 4 provided
functionObjects/specieReactionRates/specieReactionRates.C:81:25: error: ‘file’ was not declared in this scope
     writeFileHeader(file());
                     ~~~~^~
functionObjects/specieReactionRates/specieReactionRates.C:81:25: note: suggested alternative: ‘kill’
     writeFileHeader(file());
                     ~~~~^~
                     kill
functionObjects/specieReactionRates/specieReactionRates.C: In instantiation of ‘bool Foam::functionObjects::specieReactionRates<ChemistryModelType>::write() [with ChemistryModelType = Foam::rho2ChemistryModel]’:
functionObjects/specieReactionRates/specieReactionRates.C:184:1:   required from here
functionObjects/specieReactionRates/specieReactionRates.C:125:23: error: ‘file’ was not declared in this scope
         writeTime(file());
                   ~~~~^~
**....**

**Comment by vincentcasseau** [comment]
Hi,
Could you please send me the entire install log file by email (see Wiki/People and Contact).
Thank you!

**Comment by Coding4ever4CFD** [comment]
Thank you very much Vincent.

Ozgur.
