### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by iainsymthe** [vincentcasseau/hyStrath#29]
I am a retired engineer with an interest in hypersonic flows.  I was trying to install hy2foam to play around with it a bit.  Many thanks for having this resource available to the community.

I have installed OF6 (1706) and downloaded the hy2foam files 
git clone https://github.com/vincentcasseau/hyStrath.git

and tried to compile it as

cd hyStrath
./install-all.sh 8 > log.install.hy2foam 2>&1 &

I use gcc/7.3.0 and openmpi/3.1.3

The first error I get is ...

wmake ./strathChemistryModel
wmakeLnIncludeAll: running wmakeLnInclude on dependent libraries:
    wmakeLnInclude error: base directory /basepath/src/thermophysicalModels/chemistrySolver/ does not exist

 Indeed 
ls /basepath/src/thermophysicalModels/

shows chemistryModel (not chemistrySolver)
-rwxrwx---+  1   641 Nov 14 16:41 Allwmake
drwxrwx---+ 13   512 Nov 14 17:05 specie
drwxrwx---+  7   512 Nov 14 17:05 solidSpecie
drwxrwx---+  9   512 Nov 14 17:05 thermophysicalProperties
drwxrwx---+ 11   512 Nov 14 17:05 basic
drwxrwx---+ 11 32768 Nov 14 17:06 reactionThermo
drwxrwx---+  9   512 Nov 14 17:07 laminarFlameSpeed
drwxrwx---+  7   512 Nov 14 17:07 chemistryModel
drwxrwx---+  8   512 Nov 14 17:09 barotropicCompressibilityModel
drwxrwx---+  5   512 Nov 14 17:09 SLGThermo
drwxrwx---+  6   512 Nov 14 17:09 solidThermo
drwxrwx---+  8   512 Nov 14 17:09 solidChemistryModel
drwxrwx---+  9   512 Nov 14 17:10 radiation

after modifying

$sendingDir/src/thermophysicalModels/strath/strathChemistryModel/Make/options to 
-I$(LIB_SRC)/thermophysicalModels/chemistryModel/lnInclude \

the error goes away but I get another set of errors (see below).

Is there an error in my compilation procedure?

Thanks

Iain

functionObjects/specieReactionRates/specieReactionRates.C: In constructor ‘Foam::functionObjects::specieReactionRates<ChemistryM
odelType>::specieReactionRates(const Foam::word&, const Foam::Time&, const Foam::dictionary&)’:
functionObjects/specieReactionRates/specieReactionRates.C:81:21: error: there are no arguments to ‘file’ that depend on a templa
te parameter, so a declaration of ‘file’ must be available [-fpermissive]
     writeFileHeader(file());
                     ^~~~
functionObjects/specieReactionRates/specieReactionRates.C:81:21: note: (if you use ‘-fpermissive’, G++ will accept your code, bu
t allowing the use of an undeclared name is deprecated)
functionObjects/specieReactionRates/specieReactionRates.C: In member function ‘virtual bool Foam::functionObjects::specieReactio
nRates<ChemistryModelType>::write()’:
functionObjects/specieReactionRates/specieReactionRates.C:125:19: error: there are no arguments to ‘file’ that depend on a templ
ate parameter, so a declaration of ‘file’ must be available [-fpermissive]
         writeTime(file());
                   ^~~~
functionObjects/specieReactionRates/specieReactionRates.C:126:9: error: there are no arguments to ‘file’ that depend on a templa
te parameter, so a declaration of ‘file’ must be available [-fpermissive]
         file() << token::TAB << ri;
         ^~~~
functionObjects/specieReactionRates/specieReactionRates.C:149:13: error: there are no arguments to ‘file’ that depend on a templ
ate parameter, so a declaration of ‘file’ must be available [-fpermissive]
             file() << token::TAB << sumVRRi/V;
             ^~~~
functionObjects/specieReactionRates/specieReactionRates.C:152:9: error: there are no arguments to ‘file’ that depend on a templa
te parameter, so a declaration of ‘file’ must be available [-fpermissive]
         file() << nl;
         ^~~~
functionObjects/specieReactionRates/specieReactionRates.C:155:5: error: there are no arguments to ‘file’ that depend on a templa
te parameter, so a declaration of ‘file’ must be available [-fpermissive]
     file() << nl << endl;
     ^~~~
functionObjects/specieReactionRates/specieReactionRates.C: In instantiation of ‘Foam::functionObjects::specieReactionRates<Chemi
stryModelType>::specieReactionRates(const Foam::word&, const Foam::Time&, const Foam::dictionary&) [with ChemistryModelType = Fo
am::rho2ChemistryModel]’:
/lcrc/project/NE_SciDAC/shashi/gccOpenFoam6/OpenFOAM/OpenFOAM-6/src/OpenFOAM/lnInclude/functionObject.H:173:9:   required from ‘
static Foam::autoPtr<Foam::functionObject> Foam::functionObject::adddictionaryConstructorToTable<functionObjectType>::New(const 
Foam::word&, const Foam::Time&, const Foam::dictionary&) [with functionObjectType = Foam::functionObjects::specieReactionRates<F
oam::rho2ChemistryModel>]’
/lcrc/project/NE_SciDAC/shashi/gccOpenFoam6/OpenFOAM/OpenFOAM-6/src/OpenFOAM/lnInclude/functionObject.H:173:9:   required from ‘
Foam::functionObject::adddictionaryConstructorToTable<functionObjectType>::adddictionaryConstructorToTable(const Foam::word&) [w
ith functionObjectType = Foam::functionObjects::specieReactionRates<Foam::rho2ChemistryModel>]’
functionObjects/specieReactionRates/specieReactionRates.C:178:5:   required from here
functionObjects/specieReactionRates/specieReactionRates.C:79:5: error: no matching function for call to ‘Foam::functionObjects::
writeFile::writeFile(const Foam::objectRegistry&, const Foam::word&, const Foam::word&, const Foam::dictionary&)’
     )
     ^
In file included from /lcrc/project/NE_SciDAC/shashi/gccOpenFoam6/OpenFOAM/OpenFOAM-6/src/finiteVolume/lnInclude/volRegion.H:70:
0,
                 from functionObjects/specieReactionRates/specieReactionRates.H:48,
                 from functionObjects/specieReactionRates/specieReactionRates.C:26:
/lcrc/project/NE_SciDAC/shashi/gccOpenFoam6/OpenFOAM/OpenFOAM-6/src/OpenFOAM/lnInclude/writeFile.H:93:9: note: candidate: Foam::
functionObjects::writeFile::writeFile(const Foam::objectRegistry&, const Foam::word&)
         writeFile
         ^~~~~~~~~
/lcrc/project/NE_SciDAC/shashi/gccOpenFoam6/OpenFOAM/OpenFOAM-6/src/OpenFOAM/lnInclude/writeFile.H:93:9: note:   candidate expec
ts 2 arguments, 4 provided
/lcrc/project/NE_SciDAC/shashi/gccOpenFoam6/OpenFOAM/OpenFOAM-6/src/OpenFOAM/lnInclude/writeFile.H:75:9: note: candidate: Foam::
functionObjects::writeFile::writeFile(const Foam::functionObjects::writeFile&)
         writeFile(const writeFile&);
         ^~~~~~~~~
/lcrc/project/NE_SciDAC/shashi/gccOpenFoam6/OpenFOAM/OpenFOAM-6/src/OpenFOAM/lnInclude/writeFile.H:75:9: note:   candidate expec
ts 1 argument, 4 provided
functionObjects/specieReactionRates/specieReactionRates.C:81:25: error: ‘file’ was not declared in this scope
     writeFileHeader(file());
                     ~~~~^~
functionObjects/specieReactionRates/specieReactionRates.C:81:25: note: suggested alternative: ‘kill’
     writeFileHeader(file());
                     ~~~~^~
                     kill
functionObjects/specieReactionRates/specieReactionRates.C: In instantiation of ‘bool Foam::functionObjects::specieReactionRates<
ChemistryModelType>::write() [with ChemistryModelType = Foam::rho2ChemistryModel]’:
functionObjects/specieReactionRates/specieReactionRates.C:184:1:   required from here
functionObjects/specieReactionRates/specieReactionRates.C:125:23: error: ‘file’ was not declared in this scope
         writeTime(file());
                   ~~~~^~
functionObjects/specieReactionRates/specieReactionRates.C:125:23: note: suggested alternative: ‘kill’
         writeTime(file());
                   ~~~~^~
                   kill
functionObjects/specieReactionRates/specieReactionRates.C:155:9: error: ‘file’ was not declared in this scope
     file() << nl << endl;
     ~~~~^~
functionObjects/specieReactionRates/specieReactionRates.C:155:9: note: suggested alternative: ‘kill’
     file() << nl << endl;
     ~~~~^~
     kill
make: *** [Make/linux64GccDPInt32Opt/functionObjects/specieReactionRates/specieReactionRates.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by vincentcasseau** [comment]
Hi Iain,

Thanks for your interest.
There should be no need to edit paths manually. The installation script should work for any machine. If I were you, I would undo the first change you did because that may hide another problem.

The first problem to solve is the OF version you are using. OF-6 is different from OF-v1706. The former belongs to OpenFOAM.org while the latter belongs to OpenFOAM.com (ESI group). We are only supporting OF-v1706.

Regards,
Vincent

**Comment by iainsymthe** [comment]
Thanks for your quick response.  I did not realize the OF issue.  I will following instructions on https://pingpong.chalmers.se/public/courseId/8331/lang-en/publicPage.do?item=3855663

to install the ESI version.
And yes, I will go back to the paths that comes with the original git clone from hyStrath.
Thanks again,
Best wishes and thanks again for your service to the community
Iain
    On Friday, November 15, 2019, 05:18:17 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Hi Iain,

Thanks for your interest.
There should be no need to edit paths manually. The installation script should work for any machine. If I were you, I would undo the first change you did because that may hide another problem.

The first problem to solve is the OF version you are using. OF-6 is different from OF-v1706. The former belongs to OpenFOAM.org while the latter belongs to OpenFOAM.com (ESI group). We are only supporting OF-v1706.

Regards,
Vincent

**Comment by iainsymthe** [comment]
Vincent:
Is there a particular set of instructions on downloading OF-v1706?  Does one have to git checkout OpenFOAM-v1706 as a starting point?

Thanks
Iain    On Friday, November 15, 2019, 05:18:17 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Hi Iain,

Thanks for your interest.
There should be no need to edit paths manually. The installation script should work for any machine. If I were you, I would undo the first change you did because that may hide another problem.

The first problem to solve is the OF version you are using. OF-6 is different from OF-v1706. The former belongs to OpenFOAM.org while the latter belongs to OpenFOAM.com (ESI group). We are only supporting OF-v1706.

Regards,
Vincent

**Comment by vincentcasseau** [comment]
Hi Iain,

Not necessarily. On this page: https://www.openfoam.com/download/release-history.php
you can download the source .tgz files for Ubuntu (30/06/2017: OpenFOAM v1706) for both OpenFOAM and the ThirdParty.
After untaring them, simply run the `./Allwmake` in `$HOME/OpenFOAM/OpenFOAM-v1706/`

Regards,
Vincent

**Comment by iainsymthe** [comment]
Thanks again for your quick response, Vincent.  I appreciate it.  I will follow your instructions.
Best wishes,
Iain
    On Friday, November 15, 2019, 10:48:18 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Hi Iain,

Not necessarily. On this page: https://www.openfoam.com/download/release-history.php
you can download the source .tgz files for Ubuntu (30/06/2017: OpenFOAM v1706) for both OpenFOAM and the ThirdParty.
After untaring them, simply run the ./Allwmake in $HOME/OpenFOAM/OpenFOAM-v1706/

Regards,
Vincent

**Comment by iainsymthe** [comment]
Hi Vincent:
When I run ./Allwmake in $HOME/OpenFOAM/OpenFOAM-v1706/The Third party compiles OK but when it gets to compiling OpenFoam I get wclean mpiwmake  mpiwmake mpiwmakeLnInclude: linking include files to ./lnIncludemake: mpicc: Command not foundmake: mpicc: Command not found
and laterPstreamGlobals.H:41:17: fatal error: mpi.h: No such file or directory

and stops. 
Do I have to set some environment variable to point to mpicc in Third-Party?
Thanks
Iain
    On Friday, November 15, 2019, 10:48:18 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Hi Iain,

Not necessarily. On this page: https://www.openfoam.com/download/release-history.php
you can download the source .tgz files for Ubuntu (30/06/2017: OpenFOAM v1706) for both OpenFOAM and the ThirdParty.
After untaring them, simply run the ./Allwmake in $HOME/OpenFOAM/OpenFOAM-v1706/

Regards,
Vincent

**Comment by vincentcasseau** [comment]
Did you install all System Requirements?
https://www.openfoam.com/documentation/system-requirements.php
```
sudo apt-get update
sudo apt-get install build-essential flex bison cmake zlib1g-dev libboost-system-dev libboost-thread-dev libopenmpi-dev openmpi-bin gnuplot libreadline-dev libncurses-dev libxt-dev
sudo apt-get install qt4-dev-tools libqt4-dev libqt4-opengl-dev freeglut3-dev libqtwebkit-dev
sudo apt-get install libscotch-dev libcgal-dev
```

**Comment by iainsymthe** [comment]
I do not have root permission on the system I am on.  It is a Lmod based system so modules have to be loaded.I did a module purge and added the following modules  openmpi/1.10.7 and gcc/7.1.0
and the compilation is now going on ...  maybe there was some mis-match.
Thanks again for your prompt responses and helping new users.  This is indeed above and beyond the call of duty.    On Friday, November 15, 2019, 11:42:51 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Did you install all System Requirements?
https://www.openfoam.com/documentation/system-requirements.php
sudo apt-get update
sudo apt-get install build-essential flex bison cmake zlib1g-dev libboost-system-dev libboost-thread-dev libopenmpi-dev openmpi-bin gnuplot libreadline-dev libncurses-dev libxt-dev
sudo apt-get install qt4-dev-tools libqt4-dev libqt4-opengl-dev freeglut3-dev libqtwebkit-dev
sudo apt-get install libscotch-dev libcgal-dev

**Comment by iainsymthe** [comment]
Hi Vincent:
Thanks to all your help, I was able to compile OF-v1706 and hyStrath.  I will run some of the cases in the examples provided.
Thank you so very much for all your prompt responses. 
Best wishes,
Iain
    On Friday, November 15, 2019, 11:42:51 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Did you install all System Requirements?
https://www.openfoam.com/documentation/system-requirements.php
sudo apt-get update
sudo apt-get install build-essential flex bison cmake zlib1g-dev libboost-system-dev libboost-thread-dev libopenmpi-dev openmpi-bin gnuplot libreadline-dev libncurses-dev libxt-dev
sudo apt-get install qt4-dev-tools libqt4-dev libqt4-opengl-dev freeglut3-dev libqtwebkit-dev
sudo apt-get install libscotch-dev libcgal-dev

**Comment by vincentcasseau** [comment]
Thanks for your kind words, Iain.

**Comment by iainsymthe** [comment]
Hi Vincent
I was testing out the hy2Foam/cylinderReactingMach20 case (running as is with Allrun).  It diverges abruptly after T = 2.027e-5s (after running for about 4100 steps).  The dt is consistently around 5e-10.  Has anyone run this case to completion (endTime = 0.5) or noticed this failure?I am now running a case from start with Ux = 3000 (instead of 6047) to see if I can get a better flowfield for the Ux = 6047 case.
Thanks again,
Iain
    On Saturday, November 16, 2019, 05:02:23 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Thanks for your kind words, Iain.

**Comment by vincentcasseau** [comment]
Hi Iain,

Please read Issue #1 and the [Wiki](https://github.com/vincentcasseau/hyStrath/wiki/Tutorials-::-hy2Foam-::-2D-Cylinder) about this _tutorial_.

Thanks,
Vincent

**Comment by iainsymthe** [comment]
Hi Vincent:
Thanks again for your quick response and also the additional pointers.  This is all very helpful.  BTW, I did not see a blockMeshDict in the system directory, was that intentional or was it because the grid was created in some other way?
I will try to follow the steps outlined in the wiki for convergence.
Thanks again,
Iain    On Sunday, November 17, 2019, 06:04:54 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Hi Iain,

Please read Issue #1 and the Wiki about this tutorial.

Thanks,
Vincent

**Comment by vincentcasseau** [comment]
This grid is too complex to be created using the _blockMesh_ utility.  
I created the mesh using Ansys ICEM. I am not very happy with that choice for two reasons:  
- as you can see (in Paraview), the transitions across the different blocks aren't always smooth. I am sure someone could make a better mesh.
- ICEM is not open-source, which runs counter to the spirit of this project. I would eagerly accept a [Gmsh](http://gmsh.info/) mesh to replace the current grid, all the more with a replay script to change the size of the first spacing at the wall.

I have seen many people struggling with this case. Maybe you'll be fine because of your background, if not you may want to revisit this case in a couple of months once you are more familiar with OpenFOAM.

Regards,
Vincent

**Comment by iainsymthe** [comment]
Vincent:
As always, thanks for your prompt responses and advice to the user community.  
Indeed the grid is too difficult to make by blockMesh.  And yes, the problem is indeed difficult for newcomers.  Were the results in the wiki page were for the current grid (155K cells) with full chemistry (all 11 species uncommented in hTCReactionsQK)?
Since you have gotten the case to work, it is a matter of users trying their hand at many of the suggestions you have pointed out and putting in the time.  Makes it a lot easier than writing the code AND trying to solve the problem.
Best wishes and many many thanks again,
Iain
    On Sunday, November 17, 2019, 09:08:50 PM UTC, Vince <notifications@github.com> wrote:  
 
 
This grid is too complex to be created using the blockMesh utility.
I created the mesh using Ansys ICEM. I am not very happy with that choice for two reasons:
   
   - as you can see (in Paraview), the transitions across the different blocks aren't always smooth. I am sure someone could make a better mesh.
   - ICEM is not open-source, which runs counter to the spirit of this project. I would eagerly accept a Gmsh mesh to replace the current grid, all the more with a replay script to change the size of the first spacing at the wall.

I have seen many people struggling with this case. Maybe you'll be fine because of your background, if not you may want to revisit this case in a couple of months once you are more familiar with OpenFOAM.

Regards,
Vincent

**Comment by vincentcasseau** [comment]
Hi Iain,

I had multiple grids (3) with different wall refinements and the one provided is the most refined used at last.
The case in the Wiki only has two species (N2 and N). The reaction mechanisms are described in the journal article.

Thanks,
Vincent

**Comment by iainsymthe** [comment]
Thanks, Vincent.  I gradients are too large near the inlet where the grid spacing is very coarse.  I tried to get a reasonable flow field starting with the wall temp set to 250 K (instead of 1000) and a small inlet velocity (10 m/s) and slowly ramping up the inlet velocity - but even that approach the case has been diverging for Vinlet > 200 m/s.   I will try a few other things as well.
Thanks again,
Iain
    On Tuesday, November 19, 2019, 10:34:18 PM UTC, Vince <notifications@github.com> wrote:  
 
 
Hi Iain,

I had multiple grids (3) with different wall refinements and the one provided is the most refined used at last.
The case in the Wiki only has two species (N2 and N). The reaction mechanisms are described in the journal article.

Thanks,
Vincent

**Comment by vincentcasseau** [comment]
- [x ] improve Installation guidelines  
- [  ] provide script for the input mesh file of the Mach 20 cylinder testcase  
- [  ] give the steps to follow to run this case until convergence
- [  ] provide solution files

**Comment by iainsymthe** [comment]
Thanks, Vincent. Is there any documentation on the coupling of the MHD equations to hy2Foam (in hy2MhdFoam)?
Iain
    On Thursday, November 21, 2019, 12:13:04 AM UTC, Vince <notifications@github.com> wrote:  
 
 
Reopened #29.

**Comment by iainsymthe** [comment]
I have been trying to run the case with UxInlet = 20 (instead of 6047) and twall = 250 (instead of 1000) and it seems to be running stably but the dt is still 6e-10.  
Thanks
Iain

    On Thursday, November 21, 2019, 12:13:04 AM UTC, Vince <notifications@github.com> wrote:  
 
 
Reopened #29.

**Comment by vincentcasseau** [comment]
No documentation yet on MHD.

**Comment by iainsymthe** [comment]
Thanks, Vincent.  
    On Saturday, November 23, 2019, 03:59:53 PM UTC, Vince <notifications@github.com> wrote:  
 
 
No documentation yet on MHD.

**Comment by iainsymthe** [comment]
Just a quick update, a tried a few more things to get a converged flow field for the cylinder case including increasing the diffusion coefficient to 1e-3 (instead of 1e-5) but I still see the carbuncle problem (large negative velocity gradients near the symmetry line and the cylinder surface) even with the inlet velocity near 100 m/s. I even tried to run the same case with pressure set to near  1 atm ( 0.89e5 instead of 0.89) with the same effect.  Typically at t = 1e-5, the case blows up.
    On Saturday, November 23, 2019, 03:59:53 PM UTC, Vince <notifications@github.com> wrote:  
 
 
No documentation yet on MHD.

**Comment by vincentcasseau** [comment]
I am closing this issue since the last comments are unrelated to the issue's title.

**Comment by iainsymthe** [comment]
Thanks.
    On Sunday, July 5, 2020, 01:13:56 PM CDT, Vince <notifications@github.com> wrote:  
 
 


I am closing this issue since the last comments are unrelated to the issue's title.
