### ISSUE TITLE
hi, vincent, have you met carbuncle problem?

### ISSUE THREAD

**Issue by compressible** [vincentcasseau/hyStrath#3]
how do you get rid of the carbuncle problem>
somebody says AUSM is free of carbuncle problem, but I find some paper says even AUSM scheme cannot get rid of the annoying problem, have you tried that?

**Comment by vincentcasseau** [comment]
Hi there,

Interesting question but that goes beyond the scope of the current work.

The numerical procedure is that of rhoCentralFoam for now, that is the Kurganov, Noelle and Petrova central-upwind scheme. Therefore, the carbuncle problem should be present but it has not been investigated.

Thanks,

Vincent
