### ISSUE TITLE
hy2foam: command not found

### ISSUE THREAD

**Issue by tanmay8547** [vincentcasseau/hyStrath#32]
```
bash-4.2$  ./Allclean
Cleaning case /home/tanmay/hyStrath/run/hyStrath/hy2Foam/bluntedCone
bash-4.2$  ./Allrun 
Running gmshToFoam on /home/tanmay/hyStrath/run/hyStrath/hy2Foam/bluntedCone
Running checkMesh on /home/tanmay/hyStrath/run/hyStrath/hy2Foam/bluntedCone
Running hy2Foam on /home/tanmay/hyStrath/run/hyStrath/hy2Foam/bluntedCone
./Allrun: line 13: hy2Foam: command not found
Running postProcess on /home/tanmay/hyStrath/run/hyStrath/hy2Foam/bluntedCone
```

I was working on hy2foam tutorial problem and encountered the issue mentioned above.
gsmshToFoam and checkMesh are working fine but it is unable to find hy2Foam.

I am new to ubuntu and unable to resolve the issue. Kindly help to get this through.

**Comment by vincentcasseau** [comment]
Please don't run the tutorial cases from `/home/tanmay/hyStrath/run/`
but from the usual location `/home/tanmay/OpenFOAM/tanmay-v1706/run/` (or simply type the command `run`)

**Comment by tanmay8547** [comment]
Dr. Vincent,
I have tried as you mentioned, but still it is showing the same error.
The log.hy2foam says" /opt/OpenFOAM/OpenFOAM-v1912/bin/tools/RunFunctions: line 228: hy2Foam: command not found".

**Comment by vincentcasseau** [comment]
We do not support this version of OpenFOAM. The installation must have been unsuccessful. Please have a look at the Wiki.

**Comment by tanmay8547** [comment]
yes sir. i have checked the wiki. but when we clicked the links that have been provided, it takes us to v1912 rather than v1706.

**Comment by vincentcasseau** [comment]
Could you please tell me which one? I checked them all and I can't find anything wrong.

**Comment by tanmay8547** [comment]
I opened this one as mentioned "https://www.openfoam.com/releases/openfoam-v1706."
It says "OpenCFD Release OpenFOAM®  v1706". 
Then i went on "Pre-compiled binary installation for Linux systems".
After opening the above link and downloading the scripts 
    installOpenFOAM
    startOpenFOAM,
In startOpenFOAM file that the version mentioned is v1912.

**Comment by vincentcasseau** [comment]
This has to do with the ESI Group website, all links on hyStrath are pointing to the right version. I will add this link then:
https://www.openfoam.com/download/release-history.php
Please scroll down to the right version.

**Comment by tanmay8547** [comment]
Thank you Dr. Vincent for giving time on the issue. i will install v1706 by the way you mentioned. :)

**Comment by tanmay8547** [comment]
```
```
tanmay@tanmay:~/OpenFOAM/tanmay-v1706$ git clone https://github.com/vincentcasseau/hyStrath.git --branch master --single-branch && cd hyStrath/
Cloning into 'hyStrath'...
remote: Enumerating objects: 334, done.
remote: Counting objects: 100% (334/334), done.
remote: Compressing objects: 100% (249/249), done.
remote: Total 11713 (delta 105), reused 216 (delta 70), pack-reused 11379
Receiving objects: 100% (11713/11713), 624.99 MiB | 100.00 KiB/s, done.
Resolving deltas: 100% (6024/6024), done.
Checking connectivity... done.
Checking out files: 100% (5321/5321), done.
tanmay@tanmay:~/OpenFOAM/tanmay-v1706/hyStrath$ ls
applications              install-MHD.sh  resync-hybridPICDSMC.sh
doc                       LICENSE.txt     resync-MHD.sh
install-all.sh            README.md       run
install-CFD.sh            resync-all.sh   src
install-DSMC.sh           resync-CFD.sh
install-hybridPICDSMC.sh  resync-DSMC.sh
tanmay@tanmay:~/OpenFOAM/tanmay-v1706/hyStrath$ sh ./install-CFD.sh 2 > logInstall 2>&1 &
[1] 3766
tanmay@tanmay:~/OpenFOAM/tanmay-v1706/hyStrath$ 
```
I am stuck here sir. Not sure what to do in this case since i am a beginner in linux. Openfoam is correctly installed and i ran the tutorials of openfoam and they work fine. i have followed the steps as mentioned in the respective pages but still not able to compile it.

**Comment by vincentcasseau** [comment]
You ran the install command
`sh ./install-CFD.sh 2 > logInstall 2>&1 &`
but didn't report error. Please browse `logInstall` and copy-paste the error.

**Comment by tanmay8547** [comment]
Sir, The logInstall showed
mkdir : missing operand
Try 'mkdir --help' for more information

**Comment by vincentcasseau** [comment]
What is happenning when you type the commands:
`src`
and then
`run`?

If both of them run normally, could you please send me logInstall by email (see Wiki/Contacts).

**Comment by tanmay8547** [comment]
when i put `run` after `src`, it shows ` bash: cd: /home/tanmay/OpenFoam/tanmay-v1706/run : No such file or directory`

**Comment by vincentcasseau** [comment]
And this echoes to my first comment in this thread. You need to create the `run` directory in your OpenFOAM user folder `~/OpenFOAM/tanmay-v1706.` This is usually the last step when installing any version of OpenFOAM.

`mkdir -p ~/OpenFOAM/tanmay-v1706/run`
then
`sh ./install-CFD.sh 2 > logInstall 2>&1 &`

I would say that you first need to familiarize yourself with OpenFOAM, running tutorial cases for simpleFoam, icoFoam, and rhoCentralFoam. Once you have a good understanding of the different dictionaries and files composing a test case, it will be easier for you to use hyFoam, etc.
