### ISSUE TITLE
Adding heat source to hy2Foam with fvOptions 

### ISSUE THREAD

**Issue by iainsymthe** [vincentcasseau/hyStrath#33]
Is it possible to use topoSetDict and fvOptions to add a heat source with hy2Foam?

**Comment by vincentcasseau** [comment]
I've used topoSetDict with dsmcFoam+ once. This is only the only time I've been using these two utilities so I can't really say. The best would be to try and report any problem.

**Comment by iainsymthe** [comment]
Thanks Vince.When I tried to run topoSet, I see the following
Create time
--> FOAM Warning :     From function void* Foam::dlOpen(const Foam::fileName&, bool)    in file POSIX.C at line 1321    dlopen error : OpenFOAM/user-v1706/platforms/linux64GccDPInt32Opt/lib/libstrathFiniteVolume.so: undefined symbol: _ZN4Foam12fvPatchFieldINS_6TensorIdEEE31patchMapperConstructorTablePtr_E--> FOAM Warning :     From function bool Foam::dlLibraryTable::open(const Foam::fileName&, bool)    in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 101    could not load "libstrathFiniteVolume.so"Create polyMesh for time = 0
Reading topoSetDict
Time = 0    mesh not changed.Created cellSet ignitionCells    Applying source sphereToCell    Adding cells with centre within sphere, with centre = (0.01 0 0) and radius = 0.0005    cellSet ignitionCells now size 31056End
....so it does not load the libstrathFiniteVolume.so but creates the ignition cell sets.When I run the case, it does not add the heat source - I see a warning saying fvOptions has been read but not used.
I know the set-up works because I have used the same topoSetDict file with reactingFoam and I can see the temp go up.
If, based on the output you have some suggestions, it would be great.
Thanks
Iain
    On Thursday, April 30, 2020, 01:33:50 AM UTC, Vince <notifications@github.com> wrote:  
 
 


I've used topoSetDict with dsmcFoam+ once. This is only the only time I've been using these two utilities so I can't really say. The best would be to try and report any problem.

**Comment by iainsymthe** [comment]
Vince:
Do you have any suggestions to fix the issue of not being able to use topoSet with hy2Foam?I tried running the topoSetDict from hy2Foam in the dsmcFoam+/couette/couette_N2-O2/ example and it worked fine.  The controlDict file in couette_N2-O2 does not have libs ("libstrathFiniteVolume.so") to be loaded as in hy2Foam - which seems to cause the issue.

Thanks
Iain

**Comment by vincentcasseau** [comment]
Hi Iain, Thank you for the additional info. I will it a look this weekend.

**Comment by iainsymthe** [comment]
Thanks, Vince.  I will await your response.  Being able to add heat sources will enable the use of hy2Foam for detonation problems and comparing the results with other references you had suggested to another user.

**Comment by vincentcasseau** [comment]
Hi Iain,
As you can see above, I fixed the conflict between the topoSet application and the strathFiniteVolume library.  
I am also done with the necessary changes in the species continuity equations (YEqn), momentum equations (UEqn) and total energy equation (eEqnViscous). Unfortunately, I do not have available computational resources to re-run most of the regression cases. If you do, I could send you these three files by e-mail (see Wiki/Contacts).  
The first step would be to check that current tests are successful and the second step would consist in using fvOptions for a canonical problem.
Regards,
Vincent

**Comment by iainsymthe** [comment]
Thanks Vince.Yes, please send me the files and the procedure to replace the old files and recompile them.  If possible also send me a canonical problem that you would like me to test out.  I could try to run it on a few cores (so we can check out the parallel version as well).Thanks again for your efforts and service to the community.
Iain    On Saturday, May 30, 2020, 10:31:02 PM CDT, Vince <notifications@github.com> wrote:  
 
 


Hi Iain,
As you can see above, I fixed the conflict between the topoSet application and the strathFiniteVolume library.
I am also done with the necessary changes in the species continuity equations (YEqn), momentum equations (UEqn) and total energy equation (eEqnViscous). Unfortunately, I do not have available computational resources to re-run most of the regression cases. If you do, I could send you these three files by e-mail (see Wiki/Contacts).
The first step would be to check that current tests are successful and the second step would consist in using fvOptions for a canonical problem.
Regards,
Vincent

**Comment by iainsymthe** [comment]
Vince:
I have not received any of the files you were to send me to test - just a quick check to make sure nothing was lot in transit.
Thanks
Iain
    On Saturday, May 30, 2020, 10:31:02 PM CDT, Vince <notifications@github.com> wrote:  
 
 


Hi Iain,
As you can see above, I fixed the conflict between the topoSet application and the strathFiniteVolume library.
I am also done with the necessary changes in the species continuity equations (YEqn), momentum equations (UEqn) and total energy equation (eEqnViscous). Unfortunately, I do not have available computational resources to re-run most of the regression cases. If you do, I could send you these three files by e-mail (see Wiki/Contacts).
The first step would be to check that current tests are successful and the second step would consist in using fvOptions for a canonical problem.
Regards,
Vincent
