### ISSUE TITLE
Expected a word but found on line 0 an error - hy2Foam with reacting nitrogen

### ISSUE THREAD

**Issue by zonexo** [vincentcasseau/hyStrath#36]
Hi,

I'm trying to simulate a case with reacting nitrogen that dissociates and ionises. I was previously using hTCReactionsQK but I realised that it's not possible so I change to hTCReactionsDPLR.

Since it only involves nitrogen, I removed the others, leaving those involving N and e.

However, when I tried to run it, I got the error:

```
Create time

Create mesh for time = 0

Creating reaction model

Selecting hTC model laminar2<rho2ChemistryHTC>
Selecting chemistry type
{
    chemistrySolver Euler2Implicit;
    chemistryThermo rho2;
}

Selecting thermodynamics package
{
    type            heRho2Thermo;
    mixture         reacting2Mixture;
    transport       BlottnerEucken;
    thermo          decoupledEnergyModes;
    energy          sensible2InternalEnergy;
    equationOfState perfect2Gas;
    specie          advancedSpecie;
}

Selecting chemistry2Reader foam2ChemistryReader

--> FOAM FATAL IO ERROR:
Expected a word but found on line 0 an error

file: IStringStream.sourceFile at line 0.

    From function Reaction2<Reaction2Thermo>::lrhs(Istream& is)
    in file lnInclude/Reaction2.C at line 240.

FOAM exiting
```

I realised that if I use hTCReactionsQK, it works but there's only 2 reactions involving nitrogen. I tried to add the reactions form hTCReactionsDPLR but it can't work, giving the error:

```
Selecting chemistry2Reader foam2ChemistryReader


--> FOAM FATAL IO ERROR:
keyword ni is undefined in dictionary "/scratch/users/nus/tsltaywb/OpenFOAM/eilmer_finite_cylinder_hy2Foam/constant/hTCReactionsQK.reactions.nitrogenElectronImpactDissociationReaction"

file: /scratch/users/nus/tsltaywb/OpenFOAM/eilmer_finite_cylinder_hy2Foam/constant/hTCReactionsQK.reactions.nitrogenElectronImpactDissociationReaction from line 79 to line 84.

    From function const Foam::entry& Foam::dictionary::lookupEntry(const Foam::word&, bool, bool) const
    in file db/dictionary/dictionary.C at line 551.

FOAM exiting

```

I have attached the files for reference. Thanks.
[hTCReactionsQK.txt](https://github.com/vincentcasseau/hyStrath/files/4687804/hTCReactionsQK.txt)
[hTCReactionsDPLR.txt](https://github.com/vincentcasseau/hyStrath/files/4687805/hTCReactionsDPLR.txt)

**Comment by zonexo** [comment]
Btw, I realised that if I only enable reaction no 9,10 and 33, everything works fine. But if I enable no 37, I get the error mentioned above.

Also for no 49 below, how can I get the values for A0 etc?

```
// Reaction no 49
    atomicNitrogenCationNitrogenChargeExchangeReaction
    {
        type     reversibleArrheniusReaction;
        reaction "N+ + N2 = N2+ + N";
        controlT chargeExchange;
        A        1.0e09;
        beta     0.5;
        Ta       12200;

        ni       (1e20 1e21 1e22 1e23 1e24 1e25);
        A0       ("no data");
        A1       ();
        A2       ();
        A3       ();
        A4       ();
    }
```

**Comment by vincentcasseau** [comment]
Hi Wee-Beng,

I don't know why I left Reaction 49  in this dict, please remove it.
Also, I would recommend you use _hTCReactionsEarth93_ instead. This latter uses Third Body to reduce the number of reactions in the chem dict.

Your reactions are reversible. If you do not provide coeffs A0-A4, the equilibrium constant cannot be calculated.

Please see: https://github.com/vincentcasseau/hyStrath/wiki/How-to-::-Chemistry#322-reverse-reaction)
and Eq. (2.69), page 30  in https://github.com/vincentcasseau/hyStrath/blob/master/doc/PhDthesis-vincentcasseau.pdf

Thanks,
Vince
