### ISSUE TITLE
[dsmcFoam+] Axisymmetric weighting, patch / boundary values

### ISSUE THREAD

**Issue by timteichmann** [vincentcasseau/hyStrath#37]
Hi,
I have a question regarding the axisymmetric weighting in dsmcFoam+. More specifically my question is concerned with the way that the RWF is calculated during particle insertion via boundaries.

For example in `dsmcFreeStreamInflowPatch` the number of particles that are inserted on a given boundary face are calculated with `cloud_.nParticles(patchI, faceI)` (cf. l. 135ff.), which translates to `dsmcAxisymmetric::nParticles(patchI, faceI)` in case axisymmetric weighting is active. This in turn uses `pRWF(patchI, faceI)` to calculate the RWF on the patch face via `recalculatepRWF(patchI, faceI)`. This finally reveals the algorithm as
`1.0 + (maxRWF() - 1.0) * radius/radialExtent()`
where `radius = polar component of face center`.
However, the particle(s) that is/are inserted into the geometry are created with `RWF = cloud_.coordSystem().RWF(cellI)` (cf. l. 351ff.). This is calculated via `recalculateRWF(cellI)` which uses the following algorithm
`1.0 + (maxRWF() - 1.0) * radius/radialExtent()`
where `radius = polar component of cell center`.
Therefore, for finite dimensioned cells both values will never be the same. I do not understand the reasoning behind this. From my current understanding the current behavior leads to a (very, very small) number / mass / momentum / energy difference (per particle). Therefore I would initialize the particles with the RWF on the boundary. This is also the case in the other boundaries that insert particles. 

Probably my understanding is wrong or I have overlooked something, therefore I would really appreciate if you could elaborate on the reasoning behind the current implementation.

If the current behavior is indeed flawed I can prepare a patch.

Thanks in advance!
Best regards,
Tim

**Comment by vincentcasseau** [comment]
Hi Tim,
Please send me an email with the same contents: see People/Contacts in the Wiki.
Thanks,
Vincent

**Comment by vincentcasseau** [comment]
Task list:

- [ ] fix the inconsistency spotted by Tim between lines 135 & 351 in `dsmcFreeStreamInflowPatch.C` (and other in/outflow patches as well)
- [ ] rename the "particle" RWF method  
- [ ] remove the "mixed" RWF method  

RWF = radial weighting factor
