### ISSUE TITLE
Equilibrium constant - Park 1990

### ISSUE THREAD

**Issue by vincentcasseau** [vincentcasseau/hyStrath#38]
Hi,

I realized there is an inconsistency between Eq. (2.68), page 30    
(see https://github.com/vincentcasseau/hyStrath/blob/master/doc/PhDthesis-vincentcasseau.pdf)
and the source code when forward and backward controlling temperatures differ (i.e., for dissociation & associaive ionization reactions).

What was intended:
kb(Tcb) = kf(**Tcb**) / Keq(Tcb)     .........   (Eq. 2.68)

Currently in the source code:
kb(Tcb) = kf(**Tcf**) / Keq(Tcb)

where Tcf and Tcb are the forward and backward controlling temperatures, respectively.

Does anyone have access to Park's 1990 book (I don't until libraries reopen) and could confirm that Eq. (2.68) is indeed correct? This is an easy fix but I would like to be 100% sure.

Thanks,
Vince

**Comment by vinayukp** [comment]
Hi, 
   I have the book. Would you like me to check some details?

regards
Vinay

**Comment by vincentcasseau** [comment]
Hi Vinay,
That would be great if you could :)
Thanks,
Vince

**Comment by vinayukp** [comment]
Hi Dr. Vince,
                    I found this statement in Park 1990 book, Page 272-273

" The rate coefficients for the reverse reactions to the above three dissociative recombination process, that is the associative ionization rates, are calculated from the above three expressions assuming that the forward and reverse rates are related by the equilibrium constants evaluated at the electron temperature Te"..

Does this mean --   kb(Tcb) = kf(Tcb) / Keq(Tcb) ?
Is it ok to share the relevant pages from the book (scanned) here? Do let me know..
Regards
Vinay

**Comment by vincentcasseau** [comment]
Hi Vinay,
Since Tcf = Ttr and Tcb = Te for associative ionization reactions, I would seem that  kb(Tcb) = kf(Tcb) / Keq(Tcb) indeed.
I understand you may not want to share scans publicly. Please feel free to send them to me by email (see: Wiki/Contacts) and I will double-check.
Many thanks,
Vince
