### ISSUE TITLE
dsmcFoam+: Absorbed parcels do not contribute to q and fD boundary fields

### ISSUE THREAD

**Issue by timteichmann** [vincentcasseau/hyStrath#49]
As already outlined in #43 I think that in the currently implementation absorbed parcels are completely ignored in the calculation of `qBF` and `fDBF` (boundary fields) because `measurePropertiesAfterControl` is never called when a parcel is absorbed.

Note, that this was also not the case before the referenced merge request, I just discovered it while working on it

Edit: Woops, I should maybe add the files in question: dsmcAbsorbingDiffuseWallPatch.C, specifically line 122 and the function `absorbParticle` in dsmcAbsorbingWallPatch.C lines 157-182.

**Comment by vincentcasseau** [comment]
I modified the `void dsmcAbsorbingWallPatch::absorbParticle(dsmcParcel& p, dsmcParcel::trackingData& td)` function to address this problem. Please let me know what you think before I commit this change.

Original:
```c++
    // Update the boundaryMeasurement relative to this absorbing patch
    cloud_.boundaryFluxMeasurements().updatenAbsorbedParticlesOnPatch
    (
        wppIndex,
        wppLocalFace,
        nAbsorbedParticles
    );
```

Proposed solution:
```c++
    // Update the boundaryMeasurement relative to this absorbing patch
    const label spId = p.typeId();
    const scalar fA = mag(wpp.faceAreas()[wppLocalFace]);
    const scalar deltaT = cloud_.deltaTValue(p.cell());
    
    const vector postIMom = vector::zero;
    const scalar postIE = 0.0;
    
    const scalar deltaQ = nAbsorbedParticles*(this->preIE_ - postIE)/(deltaT*fA);
        
    const vector deltaFD = nAbsorbedParticles*(this->preIMom_ - postIMom)/(deltaT*fA);    
        
    cloud_.boundaryFluxMeasurements().speciesqBF(spId, wppIndex, wppLocalFace) += deltaQ;

    cloud_.boundaryFluxMeasurements().speciesfDBF(spId, wppIndex, wppLocalFace) += deltaFD;
        
    cloud_.boundaryFluxMeasurements().updatenAbsorbedParticlesOnPatch
    (
        wppIndex,
        wppLocalFace,
        nAbsorbedParticles
    );
```

**Comment by timteichmann** [comment]
Hi Vincent,
From first glance this looks like a very elegant solution. A nitpick: I would not introduce the `postIMom` and `postIE` (vector and scalar) as they have no functional relevance. However, they are probably killed off by the compiler anyways. As the code can becomes less readable if they are removed I would suggest to replace them by a small comment explaining the rationale.

**Comment by vincentcasseau** [comment]
Hi Tim, Thanks for the advice, this is reflected in commit ba72df41b69005ac247ab796004866add09fb344.
However, I made a mistake in the commit message and referred to #42 instead of #49...
