### ISSUE TITLE
electrical conductivity model in hy2mhdFoam - SpitzerHarm model

### ISSUE THREAD

**Issue by iainsymthe** [vincentcasseau/hyStrath#58]
I am trying to use the SpitzerHarm conductivity model with mhdproperties file set as 
mhd             true;

mhdModel        lowReMag;

collisionData   Gupta1989D;//constant;

conductivityModel SpitzerHarm;//;//Bush;Boltzmann

//T0              12000;

//n               2;

//sigma0          1;//5100 for Bush

hallEffect      true;

but I get as error as 
Selector 2: Selecting mhdModel lowReMag
Selector 2 returning
Constructor 1 was used
conductivity model initialising.
Looking for conductivityModel name 
Selecting conductivityModel SpitzerHarm
Creating SpitzerHarm conductivity model
conductivity model initialised.
[39] 
[39] 
[39] --> FOAM FATAL ERROR: 
[39] Different dimensions for =
     dimensions : [-1 -3 3 0 0 2 0] = [1 -1 -3 0 0 0 0]
[39] 
[39] 
[39]     From function bool Foam::dimensionSet::operator=(const Foam::dimensionSet&) const
[39]     in file dimensionSet/dimensionSet.C at line 171.
[39] 
FOAM parallel run aborting

I tried the collision data model set to constant and Gupta89D with the same result.  I also tried an option with  Sigma0 = 1.0 but got the same error.  Can a sample mhdproperties file be provided with the correct settings for the SpitzerHarm options?

**Comment by vincentcasseau** [comment]
Hi Iain,

Thanks for reporting this bug.

I will wait until the ISRO-dev branch is merged into main (master) before addressing this issue. The source code was cleaned and improved, and the MHD dictionary structure was changed a bit.
I will leave these 2 Issues open until that is done.

Regards,
Vincent

**Comment by iainsymthe** [comment]
Thanks, Vincent. Let me know when I should sync/update my code.  Also, the hy2MhDFoam solver does not solve the EM equations as in MhDFoam. Any plans on coupling the EM equations with the NS equations as in MhDFoam in hy2Foam but with variable electrical conductivity?  
Thanks
Iain
    On Tuesday, December 15, 2020, 12:29:05 PM CST, Vince <notifications@github.com> wrote:  
 
 


Hi Iain,

Thanks for reporting this bug.

I will wait until the ISRO-dev branch is merged into main (master) before addressing this issue. The source code was cleaned and improved, and the MHD dictionary structure was changed a bit.
I will leave these 2 Issues open until that is done.

Regards,
Vincent

**Comment by vincentcasseau** [comment]
@ARyakhovskiy got his PhD degree a while ago, so I doubt there will be new additions unless someone's takes over.

**Comment by iainsymthe** [comment]
Thanks, Vincent.      On Sunday, December 20, 2020, 11:29:12 AM CST, Vince <notifications@github.com> wrote:  
 
 


@ARyakhovskiy got his PhD degree a while ago, so I doubt there will be new additions unless someone's takes over.

**Comment by ARyakhovskiy** [comment]
Hey, everyone!

Making a coupled solver for a full system of MHD equations is something
thats on my agenda. I am currently getting a student involved in the
project, who'll hopefully be developing it as his bach and masters degree
project. However, I can't yet tell you any timeline of this development.

Best regards,
Alexey

пн, 21 дек. 2020 г., 17:56 iainsymthe <notifications@github.com>:

> Thanks, Vincent.   On Sunday, December 20, 2020, 11:29:12 AM CST, Vince <

**Comment by vincentcasseau** [comment]
Hi Alexey,

That's great to hear, thanks for commenting!

Take care,
Vincent

**Comment by iainsymthe** [comment]
Thanks for the update, Alexey.  Would it be possible to add a short note to the README file in the  NASA_MSL_forebody_NR-MHD example explaining the physical set-up of the problem and also some more information on the geometry used in the example?  The README file gives a link to a pdf but no information on the geometry itself.
Thanks,
Iain
    On Monday, December 21, 2020, 09:03:14 AM CST, Alexey Ryakhovskiy <notifications@github.com> wrote:  
 
 

Hey, everyone!

Making a coupled solver for a full system of MHD equations is something
thats on my agenda. I am currently getting a student involved in the
project, who'll hopefully be developing it as his bach and masters degree
project. However, I can't yet tell you any timeline of this development.

Best regards,
Alexey

пн, 21 дек. 2020 г., 17:56 iainsymthe <notifications@github.com>:

> Thanks, Vincent. On Sunday, December 20, 2020, 11:29:12 AM CST, Vince <

**Comment by vincentcasseau** [comment]
Hi Iain,

It would seem that this bug was fixed last Summer in the dev-isro-1 branch (now merged into master). I ran the [MSL-NR-MHD](https://github.com/vincentcasseau/hyStrath/tree/master/run/hyStrath/hy2MhdFoam/NASA_MSL_forebody_NR-MHD) test case with the SpitzerHarm electrical conductivity model and it ran. Same observation for the other available models:

- Bush
- constantElectricalConductivity
- ChapmanCowling
- Raizer

Thanks,
Vincent
