### ISSUE TITLE
Question about charge neutrality with multiple ionic species

### ISSUE THREAD

**Issue by iainsymthe** [vincentcasseau/hyStrath#60]
Is there some place where charge neutrality is enforced in h2yFoam (and hy2MhdFoam)?  Since all species transport equations are solved independently with their own source terms, if charge neutrality is not enforced, then it is likely that the sum of positive charge densities might not equal the negative charge densities at every time step/location.
Any insight into this will be helpful.

Thanks
Iain

**Comment by Alex070720** [comment]
Hello Iain,

enforced is may be a not quite correct expression.

I will soon take a closer look at the modeling of diffusion processes with hy2Foam.  But I haven't had much time for that so far. It is probably about the calculation of the diffusion fluxes. These are calculated here if I understood it correctly: /src/thermophysicalModels/strath/strathSpecie/transport/speciesDiffusion/multiSpeciesTransportModels/multiSpeciesTransportModel/multiSpeciesTransportModel.C.

It is supposed to be something like ambipolar diffusion. I don't know yet if it is correct. I think it is not quite correct, but I am not sure yet! As soon as I find the time I will try to implement something similar to the paper of J. D. Ramshaw and C. H. Chang: "Computational Fluid Dynamics Modeling of Multicomponent Thermal Plasmas." There it is shown how to implement ambipolar diffusion.

Regards,

Alex

**Comment by iainsymthe** [comment]
Thanks for your note, Alex.  Let me know when you get a chance to look into it.  Having the ability to model thermal plasmas will be an useful addition to hy2Foam.  
Iain    On Thursday, December 3, 2020, 08:21:13 AM CST, Alex070720 <notifications@github.com> wrote:  
 
 


Hello Iain,

enforced is may be a not quite correct expression.

I will soon take a closer look at the modeling of diffusion processes with hy2Foam. But I haven't had much time for that so far. It is probably about the calculation of the diffusion fluxes. These are calculated here if I understood it correctly: /src/thermophysicalModels/strath/strathSpecie/transport/speciesDiffusion/multiSpeciesTransportModels/multiSpeciesTransportModel/multiSpeciesTransportModel.C.

It is supposed to be something like ambipolar diffusion. I don't know yet if it is correct. I think it is not quite correct, but I am not sure yet! As soon as I find the time I will try to implement something similar to the paper of J. D. Ramshaw and C. H. Chang: "Computational Fluid Dynamics Modeling of Multicomponent Thermal Plasmas." There it is shown how to implement ambipolar diffusion.

Regards,

Alex

**Comment by vincentcasseau** [comment]
Hi,
If you are referring to Eq. 4 in the Ramshaw and Chang paper, then this is already done.
Please feel free to double-check it and reopen this issue if you notice a problem.
Regards,
Vincent

**Comment by iainsymthe** [comment]
Thanks for the updates, Vincent.  Should I resync my code?  My last resync update was in July 2020.
Thanks
Iain
    On Thursday, December 24, 2020, 07:19:22 PM CST, Vince <notifications@github.com> wrote:  
 
 


Hi,
If you are referring to Eq. 4 in the Ramshaw and Chang paper, then this is already done.
Please feel free to double-check it and reopen this issue if you notice a problem.
Regards,
Vincent

**Comment by Alex070720** [comment]
Hi Vincent,

I have seen that equation 4 from the Ramshaw and Chang paper is now implemented, but I haven't found equation 5. This is the ambipolar part of the diffusion of ionic species. Do you plan to implement equation 5? Or is it allready done and hidden somewhere and I just can't find it?

Regards

Alexander

**Comment by vincentcasseau** [comment]
Hi Alex,

I reopened the Issue. There are a few things I am unsure about the current implementation. I will keep you updated.
Thanks for the clarification. No, I am not planning on implementing this term soon.

Regards,
Vincent

**Comment by vincentcasseau** [comment]
Collision integrals: see bug fixes in commits 8730852b23a87d54ffe4e4c699f9b69c2cc082d5, d0fd647f52a842b485f07ea12f7ad3503727dba2, 9a9f33860debdf8cf39861816c137bc594aa6fcc, 11b06e77db696208ac26b4bb6540e39ff99f96d0, a5f020d87677e47a7119e12d484f4a3b79d46b0f, f10c3afbd80a6aa52d97042e7ed41b1b4c593dfc, 6af0d82941b8b33d979c46ea36095451b466ec29
