### ISSUE TITLE
5 species , 5 reactions Park 94 model.

### ISSUE THREAD

**Issue by tanmay8547** [vincentcasseau/hyStrath#62]
Greetings Professor,

I have simulated non - equilibrium for RAMC-II configuration with 5 species and 5 reaction with hTCReactionsEarth93 model. 

The non-equilibrium ran fine for the configuration, validated with existing literature. Then , i switched to thermal equilibrium. There the solution blew away. 

I have changed to "downgradeToSingleTv - no;" and "downgradeToSingleTemperature yes;" That is the only change that i have made with respect to non-equilibrium flow simulation.

I am attaching the log. Kindly let me know if i have to make some more changes.
Thankyou!!

[hyFoam.txt](https://github.com/vincentcasseau/hyStrath/files/5612805/hyFoam.txt)

**Comment by vincentcasseau** [comment]
Hi Tanmay,

Yes, 
> "downgradeToSingleTv - no;" and "downgradeToSingleTemperature yes;"

is enough.

Your max CFL is above 0.5. Please set a lower bounding value in system/controlDict.

Regards,
Vincent
