### ISSUE TITLE
fireII example with hy2DyMFoam crashes with core dump

### ISSUE THREAD

**Issue by iainsymthe** [vincentcasseau/hyStrath#68]
When the fire-II example with 11 species is run with 

the dynamicMeshDict file show in the "Adaptive mesh refinement" section of 
https://vincentcasseau.github.io/how-tos-cfd-fleming/how-tos-cfd-fleming-advanced/

crashes with a core dump.

After the specified number of steps = refinementInterval, 
The log file shows
Selected 4748 cells for refinement out of 11682.
Refined from 11682 to 44918 cells.

followed by

Selected 0 split points out of a possible 4748.
Execution time for mesh.update() = 0.07 s
*** Error in `hy2DyMFoam': corrupted double-linked list: 0x00000000022739c0 ***

**Comment by vincentcasseau** [comment]
Hi Iain,
Could you please run the same simulation using the single-temperature model instead?
If I remember well, this is where the problem lies (allocation of two-temperature fields at solver level).
Thanks,
Vincent

**Comment by iainsymthe** [comment]
Vincent:
Even with the single-temperature settings in constant/thermophysicalProperties I get the same error - case crashes and dumps core Just before crashing the output looks like 
Selected 0 split points out of a possible 2295.Execution time for mesh.update() = 0.28 sdiagonal:  Solving for rho, Initial residual = 0, Final residual = 0, No Iterations 0*** Error in `hy2DyMFoam': free(): invalid size: 0x0000000004eb5620 ***======= Backtrace: =========
Thanks
Iain
    On Wednesday, January 13, 2021, 11:52:22 AM CST, Vince <notifications@github.com> wrote:  
 
 


Hi Iain,
Could you please run the same simulation using the single-temperature model instead?
If I remember well, this is where the problem lies (allocation of two-temperature fields at solver level).
Thanks,
Vincent

**Comment by vincentcasseau** [comment]
I couldn't reproduce this bug.

**Comment by iainsymthe** [comment]
Could you please send me your dynamicMeshDict file?  I have attached the file I used.  I restarted from a solution that had run for 1e-6 sec.Thanks

    On Sunday, January 31, 2021, 08:55:29 PM CST, Vince <notifications@github.com> wrote:  
 
 


I couldn't reproduce this bug.

**Comment by vincentcasseau** [comment]
I understand now, I was using AMR for the non-reacting case.
Each one of the two features below causes the case to crash. I will investigate this later.
- [ ] chemistry
- [ ] slip and jump BCs

**Comment by iainsymthe** [comment]
Thanks, Vince.  I will await your instructions when you get some time to fix the issue.
    On Wednesday, March 10, 2021, 08:09:12 AM CST, Vince ***@***.***> wrote:  
 
 


I understand now, I was using AMR for the non-reacting case.
Each one of the two features below causes the case to crash. I will investigate this later.
   
   -  chemistry
   -  slip and jump BCs

**Comment by vincentcasseau** [comment]
Hi Iain,

It's fixed. That being said
1. I **strongly** discourage anyone to use the velocity slip and temperature jump boundary conditions in _hy2DyMFoam_ or it will blow up very quickly. Instead, one should use _hy2DyMFoam_ with Dirichlet BCs for temperature(s) and velocity and then use _hy2Foam_ with Robin BCs on the latest grid;
2. I would even discourage anyone to use _hy2DyMFoam_ for high-Mach external aerodynamics. As you know, _hy2Foam_ meshes need to be structured, carefully aligned with the bow shock and refined in its vicinity.

Regards,
Vincent
