### ISSUE TITLE
Compilation of the hyTwoFoam library on Ubuntu 20.04

### ISSUE THREAD

**Issue by craigwhite87** [vincentcasseau/hyStrath#69]
On Ubuntu 20.04, using GCC-5 compiler, I am unable to get the hyTwoFoam library to compile. This is likely because the compiler picks up errors in the code that older versions included with previous versions of Ubuntu don't. For example, in the Reaction2I.H file, the first function must be removed for the compilation to continue. This error was also present in the OpenFOAM-v1706 base. 

I also get these 4 errors that I haven't been able to solve yet:

n file included from fields/fvPatchFields/derived/rampInlet/rampInletFvPatchFields.H:29,
                 from fields/fvPatchFields/derived/rampInlet/rampInletFvPatchFields.C:26:
fields/fvPatchFields/derived/rampInlet/rampInletFvPatchField.H: In member function ‘Foam::scalar Foam::rampInletFvPatchField<Type>::amplitude() const’:
fields/fvPatchFields/derived/rampInlet/rampInletFvPatchField.H:216:24: error: cannot convert ‘const Foam::autoPtr<Foam::Function1<double> >’ to ‘Foam::scalar’ {aka ‘double’} in return
  216 |                 return amplitude_;
      |                        ^~~~~~~~~~
      |                        |
      |                        const Foam::autoPtr<Foam::Function1<double> >
fields/fvPatchFields/derived/rampInlet/rampInletFvPatchField.H: In member function ‘Foam::scalar& Foam::rampInletFvPatchField<Type>::amplitude()’:
fields/fvPatchFields/derived/rampInlet/rampInletFvPatchField.H:221:24: error: invalid initialization of reference of type ‘Foam::scalar&’ {aka ‘double&’} from expression of type ‘Foam::autoPtr<Foam::Function1<double> >’
  221 |                 return amplitude_;
      |                        ^~~~~~~~~~
fields/fvPatchFields/derived/rampInlet/rampInletFvPatchField.H: In member function ‘Foam::scalar Foam::rampInletFvPatchField<Type>::timeDuration() const’:
fields/fvPatchFields/derived/rampInlet/rampInletFvPatchField.H:227:24: error: cannot convert ‘const Foam::autoPtr<Foam::Function1<double> >’ to ‘Foam::scalar’ {aka ‘double’} in return
  227 |                 return timeDuration_;
      |                        ^~~~~~~~~~~~~
      |                        |
      |                        const Foam::autoPtr<Foam::Function1<double> >
fields/fvPatchFields/derived/rampInlet/rampInletFvPatchField.H: In member function ‘Foam::scalar& Foam::rampInletFvPatchField<Type>::timeDuration()’:
fields/fvPatchFields/derived/rampInlet/rampInletFvPatchField.H:232:24: error: invalid initialization of reference of type ‘Foam::scalar&’ {aka ‘double&’} from expression of type ‘Foam::autoPtr<Foam::Function1<double> >’
  232 |                 return timeDuration_;

As I say, these are errors that older versions of the GCC compiler didn't pick up and so the code compiled.

**Comment by vincentcasseau** [comment]
Hi Craig,

I would not say that this is an error that the previous compiler did not pick up but a different convention: C++11 vs. C++14 or C++17. Some deprecated features of C++11 may cause these errors.
The best would be to migrate everything to a newer version of OpenFOAM (using barycentric-tracking in DSMC). More realistically, matching the versions of gcc and OpenMPI found in Ubuntu 18.04 and the compilation should be successful (it's been tested last August).

```
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
mpirun --version
mpirun (Open MPI) 2.1.1
```

Cheers.

**Comment by craigwhite87** [comment]
Hi Vincent,

I was compiling with gcc-5, so I wonder if this is actually too high a version of something else, like bison or flex.

The DSMC module compiled ok, which is sufficient for my use right now.
