### ISSUE TITLE
Error in initializing the dsmcFoam+ case

### ISSUE THREAD

**Issue by jaimakhijaa** [vincentcasseau/hyStrath#70]
Hello, 
I was recently trying to run the **orion107kmNR** tutorial case of **dsmcFoam+** with a few modifications of my own. When I tried initializing the case using the command _dsmcInitialize+_, I faced this error. If anyone could help me with it, I would really appreciate any help.

![Screenshot 2021-04-02 122303](https://user-images.githubusercontent.com/66073301/113389777-39e78980-93ae-11eb-82d7-26167aa3858f.jpg)

**Comment by vincentcasseau** [comment]
Hi Jai,

Yes, that's an easy one. As you can see, you are running out of memory
after seeding the domain with particules.
That means the ratio of real to simulated particles (in dsmcProperties) is
too low: you can't simulate billions and billions of particles.

Regards,
Vincent

**Comment by jaimakhijaa** [comment]
Hello Vince,
Thank you for responding to my query. But in the orion107kmNR tutorial of dsmcFoam+, the total number of real particles (in dsmcInitialiseDict) is 2.934e18 and the number of simulated particles (in dsmcProperties) is 2.6708e15 which implies the ratio of real particles to simulated particles would be 1099. In my case, the total number of real particles (in dsmcInitialiseDict) is 4.9759e18 and the total number of simulated particles (in dsmcProperties) is 17.5e6 which implies the ratio of real particles to simulated particles would be 2.84e11. Therefore, my ratio isn't too low, right? Is there any other reason that I could be facing the same error?

**Comment by vincentcasseau** [comment]
Hi Jai,

For this test case, one simulated particle represents 2.6708e15 real particles and the domain is initialized from free-stream conditions. The number density of the air mixture at the inlet is 2.934e18 m<sup>-3</sup> and the total volume of the computational domain is 584.6 m<sup>3</sup>, according to _checkMesh_. Thus, you should approximately get 2.934e18 * 584.6 / 2.6708e15 = 642,210 simulated particles using the default setup (calculation that you can double-check by running _dsmcInitialise+_).
You will get 10<sup>15</sup> / 10<sup>11</sup> more simulated particles with a ratio of  2.84e11, so approximately 6 billion.

**Comment by jaimakhijaa** [comment]
Hello Vince,
Thank you for your help, I corrected the value of nEquivalentParticles in the dsmcProperties file based on your explanation above and the case was initialized successfully.
