### ISSUE TITLE
refining Orion107kmNR example (dsmcFoam+)

### ISSUE THREAD

**Issue by iainsymthe** [vincentcasseau/hyStrath#72]
What settings does one have to change to increase the near-surface resolution in the Orion107kmNR example?
I tried addLayer true; (from false)
and refinementSurfaces
orion
        {
            // Surface-wise min and max refinement level
            level (2 2);//Apply 6-levels of refinement to satisfy y+ requirement.

but when I run snappyHexMesh with the increased level (2 2) instead of (1 1) it dumps core.  It dumps core for all levels except the default (1 1) level.

Just changing addLayer to true without any other changes decreases the number of cells from 91K to 60K.

**Comment by vincentcasseau** [comment]
Hi Iain,
This is more of a generic question about _snappyHexMesh_ that could be posted on cfd-online.
Regards,
Vincent

**Comment by vincentcasseau** [comment]
Hi Iain,

The section you copy-pasted from _snappyHexMeshDict_
```
    refinementSurfaces
    {
        orion
        {
            // Surface-wise min and max refinement level
            level (3 3);//Apply 6-levels of refinement to satisfy y+ requirement.

            // Optional specification of patch type (default is wall). No
            // constraint types (cyclic, symmetry) etc. are allowed.
            patchInfo
            {
                type wall;
                inGroups (orion);
            }
        }
```

is a subdict of  the _castellatedMeshControls_ dictionary. This means `addLayer` and this subdict are two distinct features.

If you do not wish to add layers but want to refine the surface mesh, you can increase the level index `level (3 3);` as shown above and _snappyHexMesh_ won't crash. If you want layers, you will have to look into the `addLayersControls` dict on line 272.

Thanks,
Vince
