### ISSUE TITLE
Shock tube case runs with older version of hy2Foam runs but dumps core with new version

### ISSUE THREAD

**Issue by iainsymthe** [vincentcasseau/hyStrath#74]
With build
commit 7e6c616a0ae0503a05f49142398989501992a514
Tue Jul 14 23:57:52 2020 -0400
A simple shock tube case with chemistry works fine

with build
commit 914694ffc94f14cbea5074cf1364e38218e7adf2
Date:   Tue Dec 29 19:52:01 2020 -0500
the case crashes as
Create time

Create mesh for time = 0

Creating reaction model

Selecting hTC model laminar2<rho2ChemistryHTC>
Selecting chemistry type 
{
    chemistrySolver Euler2Implicit;
    chemistryThermo rho2;
}

Selecting thermodynamics package 
{
    type            heRho2Thermo;
    mixture         reacting2Mixture;
    transport       BlottnerEucken;
    thermo          decoupledEnergyModes;
    energy          sensible2InternalEnergy;
    equationOfState perfect2Gas;
    specie          advancedSpecie;
}

Selecting chemistry2Reader foam2ChemistryReader
chemistry2Model: Number of species = 14 and reactions = 33
    using integrated reaction rate

Reading thermophysical properties

Reading field U

Creating turbulence model

Selecting turbulence model type laminar
Selecting laminar stress model Stokes

Loading the transport mixing rule:	Wilke

Loading the rarefaction parameters library

Loading the multispecies transport model:	noSpeciesDiffusion

No finite volume options present

fluxScheme: Kurganov
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib64/libc.so.6"
#3  ? at rho2ReactionThermos.C:?
#4  ? at rho2ReactionThermos.C:?
#5  Foam::he2Thermo<Foam::rho2ReactionThermo, Foam::Specie2Mixture<Foam::reacting2Mixture<Foam::BlottnerEuckenTransport<Foam::species::multiThermo<Foam::decoupledEnergyModesThermo<Foam::perfect2Gas<Foam::advancedSpecie> >, Foam::sensible2InternalEnergy> > > > >::Cp() const at ??:?
#6  ? at ??:?
#7  ? at ??:?
#8  __libc_start_main in "/lib64/libc.so.6"
#9  ? at ??:?
Floating point exception (core dumped)

Both cases are run on a single core. The newer build requires a different transportProperties file  but the settings in it as the same as the setting from the transportProperties file of the old case. Everything else is the same.

**Comment by vincentcasseau** [comment]
Hi Iain,
Could you please send me the test case that crashes.
You have many custom  reactions, I'll have a hard time isolating the bug without.
Thanks

**Comment by iainsymthe** [comment]
Hi Vincent:
I have attached the case.It is a simple 1-D shocktube case-50 to 0 is the driver with HE and 0 to 50 is a stoic-h2-air mixture.  I am using the hTCReactionsJ92 set.in the constant directory I have a file called old_transport_properties which is used for the older version of the run.  the file old_out.d is the output of the case that runs with the old version.
Thanks
Iain
    On Saturday, April 24, 2021, 10:56:12 AM CDT, Vince ***@***.***> wrote:  
 
 


Hi Iain,
Could you please send me the test case that crashes.
You have many custom reactions, I'll have a hard time isolating the bug without.
Thanks

**Comment by vincentcasseau** [comment]
Hi Iain,
I can't see any attachment.
Could you please send it to me by email?
Thanks

**Comment by iainsymthe** [comment]
I had sent the attachment via email the first time itself.  I can see the attachment in my sent folder as well.  I am resending via email again (as before).
    On Saturday, April 24, 2021, 03:30:44 PM CDT, Vince ***@***.***> wrote:  
 
 


Hi Iain,
I can't see any attachment.
Could you please send it to me by email?
Thanks

**Comment by vincentcasseau** [comment]
I know and I think that is the problem. I can't see any attachment on the website (https://github.com/vincentcasseau/hyStrath/issues/74). And I meant to send it on my gmail :)

**Comment by iainsymthe** [comment]
Vincent:
With a fresh new build commit 38fcbf512bb2d7822a0dd63b3884c5a3b31bdbbdAuthor: vincentcasseau ***@***.***>Date:   Mon Mar 29 22:24:28 2021 -0400

The previous shock-tube case runs properly.
Thanks
Iain
    On Saturday, April 24, 2021, 03:30:44 PM CDT, Vince ***@***.***> wrote:  
 
 


Hi Iain,
I can't see any attachment.
Could you please send it to me by email?
Thanks
