### ISSUE TITLE
Installation Issue - dsmcmodule (dsmcFoam+) - for openfoam-v1706 - make: *** [dsmcInitialise+] Error 2

### ISSUE THREAD

**Issue by akhil0dsmc** [vincentcasseau/hyStrath#75]
System:- Ubuntu 18.04.4 LTS (Linux) and also on Ubuntu 20.04 (WSL)

Steps followed:- 
1.for Openfoam:- https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM%2B-v1606%2B/Ubuntu
2.for dsmcFoam+ :- https://vincentcasseau.github.io/installation/

Installation error: - cannot find -lhybridStrath+
complete file:- [logInstall-DSMC.txt](https://github.com/vincentcasseau/hyStrath/files/6478943/logInstall-DSMC.txt)

file's end description
"-L/home/shock/OpenFOAM/shock-v1706/platforms/linux64GccDPInt32Opt/lib -lmeshTools -lfiniteVolume -llagrangian+ -ldecompositionMethods -ldsmcFoam+ -lhybridStrath+ -lgeneralMolecule -ldynamicMesh -ldynamicFvMesh -lOpenFOAM -ldl  \
     -lm -o /home/shock/OpenFOAM/shock-v1706/platforms/linux64GccDPInt32Opt/bin/dsmcInitialise+
/usr/bin/ld: cannot find -lhybridStrath+
collect2: error: ld returned 1 exit status
/opt/openfoam/OpenFOAM-v1706/wmake/makefiles/general:140: recipe for target '/home/shock/OpenFOAM/shock-v1706/platforms/linux64GccDPInt32Opt/bin/dsmcInitialise+' failed
make[1]: *** [/home/shock/OpenFOAM/shock-v1706/platforms/linux64GccDPInt32Opt/bin/dsmcInitialise+] Error 1
/opt/openfoam/OpenFOAM-v1706/wmake/makefiles/apps:39: recipe for target 'dsmcInitialise+' failed
make: *** [dsmcInitialise+] Error 2"

**Comment by vincentcasseau** [comment]
Hi Akhil,
Sorry about that, I forgot to remove this lib in Make/options. That will be fixed today.
Thanks

**Comment by akhil-yadav** [comment]
Hello sir, 
I want to know the reaction-chemistry is included for N2-O2 (5 species) only in dsmcFoam+ or other reactions can also be done? 

If yes, please guide me on how to use it?

Or only changing the respective parameters in chemReactDict and dsmcProperties (heatBath-5species) will work for other chemical reactions and (n number of species can be included)

I am doing simulation for Mars Pathfinder  ( This model consisted of
eight species (02,
N2, 0, N, NO, C, CO, and CO,)
while accounting for dissociation (40) and exchange
(14) reactions.)
