### ISSUE TITLE
Dimensions of Jp in pdFoam

### ISSUE THREAD

**Issue by gargtarang** [vincentcasseau/hyStrath#78]
Hi, I am learning to use pdFoam for one of my study. There is one thing I could not understand. The Jp as I check from code [here](https://github.com/vincentcasseau/hyStrath/blob/049f0af8f6db4dcdf21fb519c7842ac1ee1b853b/src/lagrangian/pic/macroscopicProperties/basic/pdEmFields/pdEmFields.H#L109) is Current Density (A/m2).
```
//- particle current density field A/m^2
volVectorField Jp_;
```
However, in definition [here](https://github.com/vincentcasseau/hyStrath/blob/049f0af8f6db4dcdf21fb519c7842ac1ee1b853b/src/lagrangian/pic/macroscopicProperties/basic/pdEmFields/pdEmFields.C#L122)

`  dimensionSet(0, 0, -2, 0, 0, 1, 0),`

It looks like (A/s2) to me. Kindly clarify.

--
Tarang

**Comment by vincentcasseau** [comment]
Thanks for reporting it, that's fixed.

**Comment by gargtarang** [comment]
Pl also fix Jp in BCs folder in PIC tutorials

-Tarang

**Comment by s42001771** [comment]
Hey Vince,

Just saw this pop-up. Current density is A/m^2. The calculation is on line
440 of
the src/lagrangian/pic/macroscopicProperties/basic/pdEmFields/pdEmFields.C.

Fix should be to update the dimensionSet.

Cheers,
CC

**Comment by vincentcasseau** [comment]
Hi Chris,

Thanks, it's been fixed. As Tarang said, I also need to update all tutos.
Congrats on your award :)

Cheers,
Vincent
