### ISSUE TITLE
Reacting chemistry model for CO2-N2

### ISSUE THREAD

**Issue by akhil-yadav** [vincentcasseau/hyStrath#79]
Hello sir,
I want to know chemical reactions are included for N2-O2 (5 species) only in dsmcFoam+ or other reactions can also be done?

If yes, please assist me on how to use it?

Is changing the respective parameters/properties in chemReactDict and dsmcProperties  (tutorial heatBath-5species) is sufficient to model other chemical reactions, including n number of species.

I am trying to do a simulation for Mars Pathfinder with chemical reactions ( This model consisted of
eight species (02,
N2, 0, N, NO, C, CO, and CO,)
while accounting for dissociation (40) and exchange
(14) reactions.)

**Comment by vincentcasseau** [comment]
Hi Akhil,

Thanks for creating a new issue (I deleted your first post).
The answer is given here: https://vincentcasseau.github.io/solvers-dsmcfoam/
under _Ongoing or planned developments_

Thanks,
Vincent

**Comment by akhil-yadav** [comment]
Thanks a lot, Sir, for such a quick response.

Would you please confirm the following? 
1. Now, only N2-O2 chemical reaction is included in dsmcFoam+ ( including dissociation, exchange, and ionisation) that too with QK model only ( As I can see in src/lagrangian/dsmc/reactions). Please correct me if I was mistaken.
2. LBVHS collision model including both rotational and vibrational modes can be used for martian (CO2 -N2)  atmosphere by changing in respective parameters in dsmcProperties.

Sir, If a possible comment on the following, that would be constructive. 
1. How to implement vacuum boundary conditions at the outlet (mentioned in https://doi.org/10.1016/j.compfluid.2010.07.014 and https://doi.org/10.1016/j.cpc.2017.09.030) as far as tutorials vacuum boundary condition is not implementated. 
2.  dsmcFoam, as well as dsmcFoam+, gives fd ( force density) how to calculate drag force from it to evaluate Cd( drag coefficient).

Thank you

**Comment by vincentcasseau** [comment]
1. yes
2. yes
3. please check the How-tos. The vacuum BC is used in the tutos.
4. _fd_ is the force density in N/m², from which you can derive the **total** drag force and then the drag coefficient

**Comment by akhil-yadav** [comment]
Thank you Sir for the clarification

2. Regarding the LBVHS (The CO2 molecule has four vibrational modes with one symmetry stretching, one asymmetry stretching, and two bending modes. The vibrational characteristic temperatures for the four modes of CO2 are taken as 1997, 3380, 960, and 960 K- https://aip.scitation.org/doi/10.1063/1.5054194). How to simulate for molecules having multivibrational modes. which charactersticVibrationalTemperature to choose or multiple can be used as input.
3. How to implement vacuum boundary condition in dsmcFoam 
4.  Total drag force can be calculated (postprocessing) by integrating fd*surface normal then drag coefficient. Correct me if was mistaken.

Thank You
