### ISSUE TITLE
hy2foam tutorials bluntedCone error

### ISSUE THREAD

**Issue by dxb0920** [vincentcasseau/hyStrath#80]
Trying to run the hy2Foam bluntedCone cases. Running it on Windows using the Windows VM system for Linux with Ubuntu. install successfully,but when I run case in  /home/OpenFOAM/dxb-v1706/run/bluntedCone/ ./Allrun, it errors.
log.hy2Foam error is:
--> FOAM FATAL IO ERROR: 
wrong token type - expected Scalar, found on line 35 the word 'uniform'
file: /home/dxb/OpenFOAM/dxb-v1706/run/bluntedCone/0/Tt.boundaryField.cone.value at line 
> 35.
    From function Foam::Istream& Foam::operator>>(Foam::Istream&, Foam::doubleScalar&)
    in file lnInclude/Scalar.C at line 107.
FOAM exiting
[log.hy2Foam.txt](https://github.com/vincentcasseau/hyStrath/files/6805260/log.hy2Foam.txt)
[log.postProcess.txt](https://github.com/vincentcasseau/hyStrath/files/6805262/log.postProcess.txt)

**Comment by vincentcasseau** [comment]
That's strange - please remove the keyword ```uniform``` on line 35.

**Comment by dxb0920** [comment]
> That's strange - please remove the keyword `uniform` on line 35.

Thanks for the reply, Dr. Casseau! I will remove and try again.

**Comment by dxb0920** [comment]
> That's strange - please remove the keyword `uniform` on line 35.
Thank you again, Dr. Casseau! The problem is already solved, but I want to consult you another question. Your tutorials are all 2D models, can hy2foam compute 3D models?if yes, can you public some 3D tutorials? if not,what need I do to slove a 3D problem?

**Comment by dxb0920** [comment]
> That's strange - please remove the keyword `uniform` on line 35.
Thank you again, Dr. Casseau! The problem is already solved, but I want to consult you another question. Your tutorials are all 2D models, can hy2foam compute 3D models?if yes, can you public some 3D tutorials? if not,what need I do to slove a 3D problem?

**Comment by vincentcasseau** [comment]
>  if not,what need I do to slove a 3D problem?
A 3D geometry and nothing else. Please check generic OpenFOAM tutos.

**Comment by dxb0920** [comment]
> > if not,what need I do to slove a 3D problem?
> 
> A 3D geometry and nothing else. Please check generic OpenFOAM tutos.
Thank you Dr.
