### ISSUE TITLE
LBVHS model for CO2 ( 4 vibrational modes)

### ISSUE THREAD

**Issue by akhil-yadav** [vincentcasseau/hyStrath#81]
Hello Sir,

Sir, whether the LBVHS collision model can be implemented for gases/molecules having multi-vibrational modes or not?
(Such as CO2 molecule having four vibrational modes with one symmetry stretching, one asymmetry stretching, and two bending modes. The vibrational characteristic temperatures for the four modes of CO2 are taken as 1997, 3380, 960, and 960 K.

If yes, how to implement it?
Which charactersticVibrationalTemperature to choose or multiple can be used as input, then in which sequence.

**Comment by vincentcasseau** [comment]
Please tell me what is not clear in the How-tos and please do not refer to an article that is a copyright infringement.
NB1: CO2 has 3 vibrational modes.
NB2: checking the CFD code's input for CO2 is not forbidden.

**Comment by akhil-yadav** [comment]
Sir, According to How-tos

vibrationalDegeneracyList  -  degeneracy of each vibrational energy mode (default is 1, list of size nVibrationalModes)
characteristicVibrationalTemperature [ K ] - characteristic vibrational temperature (list of size nVibrationalModes)

Both are supposed to be input as a list (Please correct me if wrong). 
Does the input of both lists should follow some specific sequence (for CO2, or molecules having multi-vibrational modes ) like stretching temperature first, then bending, etc., or the input can be in any order/sequence ( making sure degeneracy and characteristic list are in the same sequence)

"checking the CFD code's input for CO2 is not forbidden."
Sir, please suggest where to look as I cannot find the input code/file for CO2.


Thank you

**Comment by vincentcasseau** [comment]
No, the order does not matter. You can adopt the same convention as that of the electronic energy levels provided in _dsmcProperties_ if you want to, ie, a list sorted by increasing characteristic vibrational temperature values.
