### ISSUE TITLE
Switching off dynamic mesh in dsmcFoam+

### ISSUE THREAD

**Issue by gargtarang** [vincentcasseau/hyStrath#82]
Hello Sir,

I am doing dsmcFoam+ and I found that it uses dynamic mesh to accommodate for adaptive mesh refinement. As I am using constant mesh and it takes quite a bit of time to write mesh file in each time step. I am wondering if we can use any switch to turn off writing mesh in each timestep without going into code. One way I could think of is to replace `#include "createDynamicFvMesh.H"` on line 105 with `#include "createMesh.H"`. 
Kindly suggest

-Tarang

**Comment by vincentcasseau** [comment]
Hi Tarang,
Why would you need to write mesh files at each time step? Increase the write time.
And what do you mean exactly by "mesh files"? The `cellLevel` volScalarField?
