### ISSUE TITLE
Error to compile dsmcFoam+ in ubuntu 20.4

### ISSUE THREAD

**Issue by smsmpt** [vincentcasseau/hyStrath#83]
Dear Vincent, I am trying to compile hyStrath in ubuntu 20.4 using a compatible OpenFOAM version OF-v1706, but, unfortunately I got the following error, which I do not know how to fix it! 

Kindly, I would like to ask for your advice to resolve such error or bug!

I really do not know what is missing, Note: I am using G++ 5.3, Gcc 5.3, but I do know if you would like to recommend a specific Gcc to compatible OpenFOAM/hyStrath at ubuntu 20.4.

Thanks in advance,
Samir

**~/OpenFOAM/OpenFOAM-v1706/hyStrath$ ./install.sh 16 2>/dev/null 
-----  INSTALLATION  -----
1 - CFD module
2 - DSMC module
3 - Hybrid PIC-DSMC module
4 - CFD-MHD module
5 - All modules
-----  SYNCHRONISATION  -----
11 - CFD module
12 - DSMC module
13 - Hybrid PIC-DSMC module
14 - CFD-MHD module
15 - All modules

Enter choice: 5
[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD module
SUCCESS
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed hybrid PIC-DSMC module
FAIL: check logInstall-hybridPICDSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD-MHD module
SUCCESS**

[logInstall-hybridPICDSMC.zip](https://github.com/vincentcasseau/hyStrath/files/6932823/logInstall-hybridPICDSMC.zip)
[logInstall-DSMC.zip](https://github.com/vincentcasseau/hyStrath/files/6932824/logInstall-DSMC.zip)

**Comment by smsmpt** [comment]
I did a try to change the default Gcc 5.3 to Gcc 4.8, I got an error in all of the four modules:

[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD module
FAIL: check logInstall-DSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed hybrid PIC-DSMC module
FAIL: check logInstall-hybridPICDSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD-MHD module
FAIL: check logInstall-DSMC

Then I changed the default compiler back to Gcc 5.3, I got the earlier error at only two modules:

[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD module
SUCCESS
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed hybrid PIC-DSMC module
FAIL: check logInstall-hybridPICDSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD-MHD module
SUCCESS

**Comment by smsmpt** [comment]
I did a try to change the default Gcc 5.3 to Gcc 4.8, I got an error in all of the four modules:

[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD module
FAIL: check logInstall-CFD
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed hybrid PIC-DSMC module
FAIL: check logInstall-hybridPICDSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD-MHD module
FAIL: check logInstall-CFD-MHD

Then I changed the default compiler back to Gcc 5.3, I got the earlier error at only two modules:

[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD module
SUCCESS
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed hybrid PIC-DSMC module
FAIL: check logInstall-hybridPICDSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD-MHD module
SUCCESS

**Comment by smsmpt** [comment]
I did a try to change the default Gcc 5.3 to Gcc 4.8, I got an error in all of the four modules:

[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD module
FAIL: check logInstall-CFD
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed hybrid PIC-DSMC module
FAIL: check logInstall-hybridPICDSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD-MHD module
FAIL: check logInstall-MHD

Then I changed the default compiler back to Gcc 5.3, I got the earlier error at only two modules:

[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD module
SUCCESS
[>>>>>>>>>>>>>>>>>>>>] 100% installed DSMC module
FAIL: check logInstall-DSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed hybrid PIC-DSMC module
FAIL: check logInstall-hybridPICDSMC
[>>>>>>>>>>>>>>>>>>>>] 100% installed CFD-MHD module
SUCCESS

**Comment by vincentcasseau** [comment]
Hi Samir,

It's been discussed in #69, but not resolved. You could start by giving me the output of the command lines provided in #69.
If you are trying to install our solvers, it means you managed to install OpenFOAM v1706 and the Thirdparties with no errors. Is that right?
How did you downgrade openmpi from versions 4.x to 2.x?

I am still on Ubuntu 18.04 but I just setup a VM with Ubuntu 20.04

Thanks,
Vincent

**Comment by ashwaniassam** [comment]
Hi Samir, 

  Just saw the message while going through the issue section. I have done the installation of the hyStrath complete package multiple times now on Ubuntu 20.04. You need to just downgrade GCC present by default in 20.04 to GCC 7. Use Response 15 in the below thread.

https://www.cfd-online.com/Forums/openfoam-installation/203125-v1712-build-error.html

Further, I am attaching the bashrc file which I use in OF 1706. Note just attached it in .txt format as it was not getting uploaded otherwise. 

[bashrc.txt](https://github.com/vincentcasseau/hyStrath/files/7142476/bashrc.txt)

Also, just try to go for a clean installation OF once again.

**Comment by vincentcasseau** [comment]
That's excellent Ashwani, it works.
I will add these lines to the website.
