### ISSUE TITLE
 accommodation coefficient in dsmcfoam+

### ISSUE THREAD

**Issue by Frekby** [vincentcasseau/hyStrath#85]
Hello, is it possible to set a certain accommodation coefficient in the form of a boundary condition on the walls?

**Comment by nanoR4K** [comment]
Good morning Frekby, you have certain models with this function on dsmcfoam+
For instance, here's an entry for the dsmcCLLWallPatch model:

`dsmcPatchBoundaries
( 
    boundary
    {
        patchBoundaryProperties
        {
            patchName     obstacle;
        }

        boundaryModel        dsmcCLLWallPatch;

        dsmcCLLWallPatchProperties
        {
          normalAccommodationCoefficient            0.875;
          tangentialAccommodationCoefficient        0.875;
          rotationalEnergyAccommodationCoefficient  0.875;
          vibrationalEnergyAccommodationCoefficient 0.875;
          
          velocity             (0 0 0);
          temperature            300;

        }
    }`

I didn't take a further look into the source code, but it should contain other models like Maxwell, with similar coefficient variables Available.


Let me know if you have any more questions on this boundary condition, we can set up up together.



Best regards nanoR4K.

**Comment by Frekby** [comment]
is there any documentation or is it only in the code to look at? I didn't find anything about it on the official website. And is there a model in which the coefficients of accommodation depend on the angle of incidence

**Comment by nanoR4K** [comment]
it's under 'src/lagrangian/dsmc/boundaries/derived/patchBoundaries'

**Comment by Frekby** [comment]
tell me how to set dsmcDiffuseSpecularWallPatch

> 
> 
> it's under 'src/lagrangian/dsmc/boundaries/derived/patchBoundaries'

**Comment by nanoR4K** [comment]
Under boundariesDict, insert the following entry, changing "wall name" to your boundary name, 

`boundary
    {
        patchBoundaryProperties
        {
            patchName     Wall name;
        }

        boundaryModel        dsmcDiffuseSpecularWallPatch;

        dsmcDiffuseSpecularWallPatchProperties
        {
          
         diffuseFraction   1;      //percentage in which the wall behaves as a diffuse wall 0-1
           
          velocity             (0 0 0);
          temperature              0;

        }
    }`

**Comment by Frekby** [comment]
> 
> 
> Under boundariesDict, insert the following entry, changing "wall name" to your boundary name,
> 
> boundary
> {
> patchBoundaryProperties
> {
> patchName Wall name;
> }
> 
> ```
>     boundaryModel        dsmcDiffuseSpecularWallPatch;
> 
>     dsmcDiffuseSpecularWallPatchProperties
>     {
>       
>      diffuseFraction   1;      //percentage in which the wall behaves as a diffuse wall 0-1
>        
>       velocity             (0 0 0);
>       temperature              0;
> 
>     }
> }
> ```

But at the same time it is impossible to set the coefficient of accommodation?

**Comment by nanoR4K** [comment]
> > 
> > 
> > Under boundariesDict, insert the following entry, changing "wall name" to your boundary name,
> > 
> > boundary
> > {
> > patchBoundaryProperties
> > {
> > patchName Wall name;
> > }
> > 
> > ```
> >     boundaryModel        dsmcDiffuseSpecularWallPatch;
> > 
> >     dsmcDiffuseSpecularWallPatchProperties
> >     {
> >       
> >      diffuseFraction   1;      //percentage in which the wall behaves as a diffuse wall 0-1
> >        
> >       velocity             (0 0 0);
> >       temperature              0;
> > 
> >     }
> > }
> > ```
> 
> But at the same time it is impossible to set the coefficient of accommodation?

Right, this particular boundary condition does not use accommodation coefficients.

dsmcCLLWallPatch on the other hand, has such functionalities (tangencial, normal and energy accommodation coefficients).

Here's how to setup it:

```
boundary
    {
        patchBoundaryProperties
        {
            patchName     wall name;
        }

        boundaryModel        dsmcCLLWallPatch;

        dsmcCLLWallPatchProperties
        {
          normalAccommodationCoefficient            1;
          tangentialAccommodationCoefficient        1;
          rotationalEnergyAccommodationCoefficient  1;
          vibrationalEnergyAccommodationCoefficient 1;
          
          velocity             (0 0 0);
          temperature            0;

        }
    }
```

Please refer to the ".h" source files, each one has the model's input requirements and functionality.

**Comment by Frekby** [comment]
Thank you for the answers
