### ISSUE TITLE
hy2foam: N2+N species reaction error.

### ISSUE THREAD

**Issue by dxb0920** [vincentcasseau/hyStrath#87]
Dear Vincent:
I am trying to simulate N2+N species reaction in bluntedCone case, copy and modify profiles from tutorials, after ./Allrun, 
FOAM FATAL ERROR:N not found in table.  Valid entries: 1(N2)
    From function const T& Foam::HashTable<T, Key, Hash>::operator[](const Key&) const [with T = Foam::powerLawEuckenTransport<Foam::species::multiThermo<Foam::decoupledEnergyModesThermo<Foam::perfect2Gas<Foam::advancedSpecie> >, Foam::sensible2InternalEnergy> >*; Key = Foam::word; Hash = Foam::string::hash]
    in file /home/dxb/OpenFOAM/OpenFOAM-v1706/src/OpenFOAM/lnInclude/HashTableI.H at line 146.
FOAM exiting
Please help me to slove the problem, thanks.
[log.hy2Foam.txt](https://github.com/vincentcasseau/hyStrath/files/7077227/log.hy2Foam.txt)

**Comment by dxb0920** [comment]
Thanks, I already solve the problem when I modify the case/constant/thermoDEM.

**Comment by Peter1511ogluigi** [comment]
> Thanks, I already solve the problem when I modify the case/constant/thermoDEM.

Dear dxb0920
I have trouble getting the N2+N species reaction to work. Is there any possibility that you might be able to share your case so I can compare with my own?
/Peter

**Comment by dxb0920** [comment]
> > Thanks, I already solve the problem when I modify the case/constant/thermoDEM.
> 
> Dear dxb0920 I have trouble getting the N2+N species reaction to work. Is there any possibility that you might be able to share your case so I can compare with my own? /Peter

Hi Peter
I don't know what is your problem, if we have the same problem, you should change your "InitialConditions". I just set "Y_N2 
    0.999999999999999999999999999999;  Y_N       1e-30;",the case is convergenced. I wish it helps.
