### ISSUE TITLE
Higher relaxation time in Non-reacting N2-O2

### ISSUE THREAD

**Issue by connectsk** [vincentcasseau/hyStrath#88]
While running simulation for non-reacting N2-O2 heat bath case with VT & VV relaxations, I got higher relaxation time. I am unable to find where I have made a mistake while setting the case files. Help me to resolve the issue.

thanks,

[VT_VV_relaxation_N2_O2_heatbath_nonreacting.zip](https://github.com/vincentcasseau/hyStrath/files/7149705/VT_VV_relaxation_N2_O2_heatbath_nonreacting.zip)
![VT_VV_relaxation_N2_O2_heat_bath](https://user-images.githubusercontent.com/88218701/132991285-cf61d520-8fa0-4b2d-84c4-e471cd4bfbbf.jpeg)

**Comment by vincentcasseau** [comment]
There are two reasons:
1. Multiple vibro-electronic energy pools: currently disabled, see [website](https://vincentcasseau.github.io/how-tos-cfd-fleming/how-tos-cfd-fleming-nonequilibrium/#22-multiple-vibro-electronic-energy-pools). Use the single Tv model instead without VV.
2. You are using the wrong values for sigma_m,s, see [pp. 46-48 in my thesis](https://github.com/vincentcasseau/hyStrath/blob/master/doc/PhDthesis-vincentcasseau.pdf), paragraphs 3.1.2 & 3.1.3

Thanks
