### ISSUE TITLE
problem in intialization of Microscale Poiseuille flow case 

### ISSUE THREAD

**Issue by ethrealrishi** [vincentcasseau/hyStrath#89]
Hello Vincent,
I along with group partner were trying to simulate the Microscale Poiseuille flow test case which was there in the original dsmcFOAM+ paper. We got the case file from the given reference in the paper. When we ran the case an error "createCellZone command not found" came. We found that createCellZone utility is not there in hyStrath. We want to know whether createCellZone utility is modified in hystrath or it needs to be recreated. If it needs to be recreated can you provide us some hints.
This utility was there in the version of openFoam from where I have downloaded the case file.
[Link for case file](https://github.com/MicroNanoFlows/OpenFOAM-2.4.0-MNF)

**Comment by vincentcasseau** [comment]
Hi,
As you said, this application is available in OF-2.4.0-MNF (the OF version used for dsmcFOAM+) but is missing here.
I'll update the code to make it work in OF-v1706 and keep you updated over the weekend.
Thanks,
Vincent

**Comment by vincentcasseau** [comment]
Please pull the latest commit 4cc845d and let me know if it works.
If it does, you can close this issue. Thanks.

**Comment by ethrealrishi** [comment]
Thank you, I am very grateful for your quick response. I will let you know as soon as possible.

**Comment by ethrealrishi** [comment]
Thank you so much. I am very grateful for your quick response. I will let you know as soon as possible.

**Comment by ethrealrishi** [comment]
hello Vincent,
CreateCellZones utility is working properly. Also, I was successful in adding createFaceZones utility. The Microscale Poiseuille flow case requires use of _dsmcBinsMethod_ and _dsmcMassFluxSurface_ field models in the fieldPropertiesDict. These models are there in [this folder](https://github.com/vincentcasseau/hyStrath/tree/master/src/lagrangian/dsmc/macroscopicProperties/derived). How can I enable field model in my OF-v1706?
Thank you very much.

**Comment by vincentcasseau** [comment]
Hello,
These classes have the prefix WIP (Work In Progress - they are outdated) on hyStrath. These files are not included in make/files. You would have to add them back and debug them. I unfortunately don't think I will have time to look into that in the next couple of months.

**Comment by timteichmann** [comment]
In order to add them back you can remove the `WIP_` tag and edit this file: `hyStrath/src/lagrangian/dsmc/Make/files`. The respective lines are already included but you have to remove the comment. Of course you have to recompile dsmcFoam+ afterwards. As Vincent already pointed out, it is neither guaranteed that this compiles nor that the results are correct because the code has not been adapted to recent changes.
