### ISSUE TITLE
need some suggestion to improve Heat Flux results

### ISSUE THREAD

**Issue by connectsk** [vincentcasseau/hyStrath#92]
Hi,
I am trying to validate the HEG Cylinder case. Pressure variation along the surface of the cylinder matches with the Experimental results but there is a large variation in surface heat flux. 

Please suggest some modifications which will help me to get closure results.

![pressure](https://user-images.githubusercontent.com/88218701/141250162-9259e5c4-d6e3-4e51-b683-f5ad7242a8ac.jpeg)
![heatFlux](https://user-images.githubusercontent.com/88218701/141250170-b2c63a42-7549-4fa4-818d-ad80fe79e0ba.jpeg)
 
[cylinder.zip](https://github.com/vincentcasseau/hyStrath/files/7518370/cylinder.zip)

**Comment by vincentcasseau** [comment]
Hello,
As it stands, you are not providing enough information and I am closing this Issue.
Please add a table listing **ALL** the setup differences between Nompelis _et al._,  COOLFUILD, SU2, and hy2Foam.
Please comment on the grid(s) used and other quantities such as stagnation line data.
