### ISSUE TITLE
htcreactioneEarth93 not working

### ISSUE THREAD

**Issue by Peter1511ogluigi** [vincentcasseau/hyStrath#94]
Dear Vincent

For at start, I am running hy2Foam on ubuntu 16.04 and OF v.1612+

I am trying to simulate the turbulent flow around a blunted cone, with focus on the electron density around the object. 
I have used the "blunted cone" example which is given in the tutorials as a starting point and for now have had the simulation run perfectly without errors when enabling turbulence (I wish to look at the wake at later stage, so turbulence will be important at that point).

Now I am trying to enable chemistry, since I am looking for electron density, with htcReactionsEarth93 and I get the error posted below. I have tried changing the different directories as described in the "how tos" so I cannot seem to find what I have done wrong. When running the case with htcReactionsQK there seems to be ńo problems which I think is odd (since, as I have understood it, I only need to change the htcReactions path in thermoPhysicalProperties and add the desired htcReactions file in the constant folder ). 

I really hope you can help me

Best regards, Peter

My Error message

![Screenshot from 2022-01-07 10-38-27](https://user-images.githubusercontent.com/47326008/148524368-98587060-c49e-4327-ba07-3b196edaf458.png)

My "0" folder
![Screenshot from 2022-01-07 10-42-19](https://user-images.githubusercontent.com/47326008/148524838-fe12a423-2bfa-4752-9d96-43eb5fcfe384.png)

I have enabled all the reactions and enabled all species

![Screenshot from 2022-01-07 10-43-33](https://user-images.githubusercontent.com/47326008/148525314-65e60ff2-0a88-46bc-8d4a-60a4a789c29d.png)

My chemistryProperties

![Screenshot from 2022-01-07 10-46-11](https://user-images.githubusercontent.com/47326008/148525802-49f9c66e-b824-43e6-9872-6141fa587d05.png)

My thermoPhysicalProperties
![Screenshot from 2022-01-07 10-47-35](https://user-images.githubusercontent.com/47326008/148525893-f088616c-63bd-4bec-8b96-a46ea9191503.png)

**Comment by vincentcasseau** [comment]
Dear Peter,

> For at start, I am running hy2Foam on ubuntu 16.04 and OF v.1612+

We are no longer supporting OF v.1612+, there's been too many changes since then; https://vincentcasseau.github.io/maintenance/
I encourage you to install OF v1706.
Thanks.

Regards,
Vincent

**Comment by Peter1511ogluigi** [comment]
> Dear Peter,
> 
> > For at start, I am running hy2Foam on ubuntu 16.04 and OF v.1612+
> 
> We are no longer supporting OF v.1612+, there's been too many changes since then; https://vincentcasseau.github.io/maintenance/ I encourage you to install OF v1706. Thanks.
> 
> Regards, Vincent


Dear Vincent

For a start, thanks for the fast reply :D

I have now installed v1706, but it seems as if i still have a problem when using reactingEarth93 (reactionsQK seems to work fine though)
I get the following error

![Screenshot from 2022-01-11 09-54-53](https://user-images.githubusercontent.com/47326008/148911403-2b9a751b-64af-41ef-9850-e36d5648eb42.png)

**Comment by Peter1511ogluigi** [comment]
It seems as if it works when I run with the first reaction (oxygenTBReaction), but when i enable the second (nitrogenTBReaction) it crashes as shown in the previous comment. 
Can you see any problem with the two reactions which could cause the error?

![Screenshot from 2022-01-11 10-11-59](https://user-images.githubusercontent.com/47326008/148914192-55e82275-6086-4264-8273-0461dcbb2a3d.png)

**Comment by vincentcasseau** [comment]
I think you should stage your simulation: non-reacting first as explained here
https://vincentcasseau.github.io/tutos-hy2foam/#4-running-your-own-case

And please do not use molar as the mixing rule for multi-dimensional multi-species cases.

**Comment by Peter1511ogluigi** [comment]
I have just tried to change to non-reacting, and here the simulation runs without a problem.

I have just changed the mixing rule from molar to Wilke, however if i try to turn reactions on again the exact same error occurs
![Screenshot from 2022-01-12 11-52-11](https://user-images.githubusercontent.com/47326008/149126900-bfe26975-8fee-4510-b95e-66e987332e2a.png)

**Comment by vincentcasseau** [comment]
Are you restarting the reacting simu from the converged non-reacting solution?
Have you tried 5-species air?

**Comment by Peter1511ogluigi** [comment]
Have just tried restarting from non-reacting solution and also tried 5-species air, unfortunately in both cases I get the same error message.

**Comment by vincentcasseau** [comment]
Could you please attach your test case: 5-species air set-up with the latest folder corresponding to the converged non-reacting solution. Thanks

**Comment by vincentcasseau** [comment]
I ran one iteration using the folder you sent, no problem:

```
Mean and max Courant Numbers = 0.0208995 0.499922
deltaT = 7.55287e-10
Time = 4.800075529e-05

diagonal:  Solving for rho, Initial residual = 0, Final residual = 0, No Iterations 0
DILUPBiCG:  Solving for N2, Initial residual = 6.89189e-05, Final residual = 2.87837e-13, No Iterations 3
DILUPBiCG:  Solving for O2, Initial residual = 7.13691e-05, Final residual = 3.70842e-13, No Iterations 3
DILUPBiCG:  Solving for NO, Initial residual = 0, Final residual = 0, No Iterations 0
DILUPBiCG:  Solving for N, Initial residual = 0, Final residual = 0, No Iterations 0
DILUPBiCG:  Solving for O, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoUx, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoUy, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoUz, Initial residual = 0, Final residual = 0, No Iterations 0
smoothSolver:  Solving for Ux, Initial residual = 1.23215e-05, Final residual = 6.66387e-08, No Iterations 2
smoothSolver:  Solving for Uy, Initial residual = 3.48368e-05, Final residual = 9.9251e-08, No Iterations 2
smoothSolver:  Solving for Uz, Initial residual = 0.00445306, Final residual = 4.50421e-07, No Iterations 2
diagonal:  Solving for rhoEv, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoE, Initial residual = 0, Final residual = 0, No Iterations 0
smoothSolver:  Solving for hevel, Initial residual = 1.01083e-05, Final residual = 6.3938e-09, No Iterations 6
smoothSolver:  Solving for e, Initial residual = 6.25499e-05, Final residual = 3.55395e-08, No Iterations 8
Phase no 1.0  ExecutionTime = 19.21 s  ClockTime = 20 s  Iteration no 1 (19.21 s)
```

**Comment by Peter1511ogluigi** [comment]
I think I might have turned chemistry off in the case I sent you, if I run
without chemistry I get the same as you, however if I turn it on I get the
error

Den ons. 19. jan. 2022 kl. 12.23 skrev Vince ***@***.***>:

**Comment by vincentcasseau** [comment]
That's correct, thanks.

Here's the solution to your problem:
[how-tos-cfd-fleming-chemistry/increase-robustness](https://vincentcasseau.github.io/how-tos-cfd-fleming/how-tos-cfd-fleming-chemistry/#33--increase-robustness)

Then it works:
```
Mean and max Courant Numbers = 0.0208995 0.499922
deltaT = 7.55287e-10
Time = 4.800075529e-05

diagonal:  Solving for rho, Initial residual = 0, Final residual = 0, No Iterations 0
DILUPBiCG:  Solving for N2, Initial residual = 7.16787e-05, Final residual = 4.31705e-13, No Iterations 3
DILUPBiCG:  Solving for O2, Initial residual = 0.0015304, Final residual = 2.71399e-13, No Iterations 4
DILUPBiCG:  Solving for NO, Initial residual = 0, Final residual = 0, No Iterations 0
DILUPBiCG:  Solving for N, Initial residual = 5.2421e-06, Final residual = 2.42504e-13, No Iterations 3
DILUPBiCG:  Solving for O, Initial residual = 0.999996, Final residual = 7.46799e-14, No Iterations 6
diagonal:  Solving for rhoUx, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoUy, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoUz, Initial residual = 0, Final residual = 0, No Iterations 0
smoothSolver:  Solving for Ux, Initial residual = 1.23215e-05, Final residual = 6.66387e-08, No Iterations 2
smoothSolver:  Solving for Uy, Initial residual = 3.48368e-05, Final residual = 9.9251e-08, No Iterations 2
smoothSolver:  Solving for Uz, Initial residual = 0.00445306, Final residual = 4.50421e-07, No Iterations 2
diagonal:  Solving for rhoEv, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoE, Initial residual = 0, Final residual = 0, No Iterations 0
smoothSolver:  Solving for hevel, Initial residual = 1.01083e-05, Final residual = 6.3938e-09, No Iterations 6
smoothSolver:  Solving for e, Initial residual = 6.25499e-05, Final residual = 3.55395e-08, No Iterations 8
Phase no 1.0  ExecutionTime = 19.45 s  ClockTime = 20 s  Iteration no 1 (19.45 s)
```

**Comment by Peter1511ogluigi** [comment]
Thank you very much, the chemistry works now :D
