### ISSUE TITLE
cannot obtain a zero gradient boundary condition for species density on the wall

### ISSUE THREAD

**Issue by elimanu123** [vincentcasseau/hyStrath#95]
Hello Vincent,

I am trying to simulate the flow past a blunted cone imposing a zero-gradient boundary condition for species density on the cone. At convergence the post-processing results (see pics)  in an infinite slope for the electrons density number on the cone.

Any help will be appreciated
![gradient_e-_pb](https://user-images.githubusercontent.com/60156635/149295818-87a2e434-1da9-4c5a-8703-06bad904b51b.PNG)
.

**Comment by vincentcasseau** [comment]
Hi,
1. you're solving species mass fractions, not number densities. So you're not imposing a 0-gradient BC for Ne-
2. your lines aren't normal to the wall

Please plot all species mass fractions along this line and let us know the result.
Thanks

**Comment by elimanu123** [comment]
Hi,

I plot some of the species mass fraction along the the normal to the cone (see pictures), and only the O2+ has a zero gradient on the skin.
![electrons_mass_fraction](https://user-images.githubusercontent.com/60156635/149660760-f8de4b5c-edd0-497c-a94f-92f48b39e11a.png)
![species_mass_fraction](https://user-images.githubusercontent.com/60156635/149660763-8a2a0069-9dd4-4e0a-8d2f-09971a0a96da.png)
![blunted_cone_normal](https://user-images.githubusercontent.com/60156635/149660765-6f016e78-9b80-42d7-b3cb-6d3613b64d3c.png)

**Comment by vincentcasseau** [comment]
Hi, could you please replot this graph in log-log scale with an offset so that the x-axis starts at \<first layer height> m.
Thanks

**Comment by Peter1511ogluigi** [comment]
> Hello Vincent,
> 
> I am trying to simulate the flow past a blunted cone imposing a zero-gradient boundary condition for species density on the cone. At convergence the post-processing results (see pics) in an infinite slope for the electrons density number on the cone.
> 
> Any help will be appreciated ![gradient_e-_pb](https://user-images.githubusercontent.com/60156635/149295818-87a2e434-1da9-4c5a-8703-06bad904b51b.PNG) .

Dear elimanu123

I am also trying to simulate flow past a blunted cone. I have so far just followed the setup from the blunted cone tutorial, but I cannot seem to get the same results as you acquire (it seems as if my Tv does not seperate from the cone as yours does).
Does your BC setup differ much from the blunted cone case and if so, how?

hope you might be able to help

/Peter

**Comment by elimanu123** [comment]
Hi Peter,

In my case the Mach is 24 while in the tutorial its value is 11 which can explain the difference in your results.
