### ISSUE TITLE
Problem when using Wright2005O

### ISSUE THREAD

**Issue by Peter1511ogluigi** [vincentcasseau/hyStrath#99]
Hello 

I am trying to recreate the results from the article
[Uploading 1-s2.0-S0142727X08001057-main (1)(1).pdf…](). 
I have acquired, almost, satisfactory results when using "htcReactionsEarth93" and "Gupta1989D".
The next step, would be to run the simulation with "htcReactionsDPLR" which end up giving very satisfactory results for the mass fraction of N,O,O2,N2 and NO, but not the for NO+ and e- .
I have tried to use different collision data models, but get the same problem each time. 

My problem is that when I try to use "Wright2005O" my program crashes before it has even begun. 
my error is

![Screenshot from 2022-03-23 09-43-37](https://user-images.githubusercontent.com/47326008/159658694-98cae3c7-8135-411b-8f45-fc2b57a72d1d.png)

and I have written the following in the transportProperties
![Screenshot from 2022-03-23 09-40-14](https://user-images.githubusercontent.com/47326008/159658170-72cb9122-acf6-437a-8670-1737e5d02a83.png)

Is there something extra that needs to be added when calling "Wright2005O" compared to the other models?

I hope someone can help me

/Peter

**Comment by vincentcasseau** [comment]
Hi Peter,
Could you please email me your test case and the link to the article (your upload didn't work).
Thanks

**Comment by Peter1511ogluigi** [comment]
> 

Hi Vincent,
Have you received my email?

**Comment by Peter1511ogluigi** [comment]
> Hi Peter, Could you please email me your test case and the link to the article (your upload didn't work). Thanks

Hi Vincent,
Have you received my email?

**Comment by vincentcasseau** [comment]
No, I didn't.

**Comment by Peter1511ogluigi** [comment]
> No, I didn't.

then I have send to the wrong email -_-
Should I just send it to the mail given on https://vincentcasseau.github.io/contact/ ?

**Comment by vincentcasseau** [comment]
Yes, that's the one.

**Comment by Peter1511ogluigi** [comment]
Hi Vincent

here is the case
 DPLR_Test.zip
<https://drive.google.com/file/d/1MvLolmop4rzhwLKAZ86auR0mxMqEDyRp/view?usp=drive_web>
and the article can be found on

https://www.sciencedirect.com/science/article/pii/S0142727X08001057



Den tor. 24. mar. 2022 kl. 09.41 skrev Vince ***@***.***>:

**Comment by Peter1511ogluigi** [comment]
Hey Vincent

Have you been able to take a  look at the case? (I hope my zip file and
link to article works properly :D)

/Peter

Den tor. 24. mar. 2022 kl. 10.10 skrev Peter Bæk ***@***.***>:

**Comment by Peter1511ogluigi** [comment]
Hi Vincent
The problem I have faced is that when I run the program I do not get to do
any iterations due to the program crashing at the beginning. Since it works
on your pc I believe that I might have some issue on my own.
 I have upgraded from ubuntu 16.04 to 20.04 and is trying to install the
program once more.
My problem now is that I cannot seem to downgrade to proper gcc and g++
versions. When I run “sudo apt-get install g++-7 gcc-7” I get a response
that “package has no installation candidate”.
Have you tried getting this error before, and if so, how did you solve it?

Best
Peter


Den tir. 11. okt. 2022 kl. 11.38 skrev Vince ***@***.***>:

**Comment by Peter1511ogluigi** [comment]
Hi Vincent

When doing this my terminal says:

Some packages could not be installed.this may mean that you have requested
an impossible situation or if you are using the unstable distribution that
some requires packages have not yet been created or been moved out of
incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
Libc6-dev : Breaks: libgcc-7-dev (< 7.5.0-6~) but 7.3.0-16ubuntu3 is to be
installed
E: unable to correct problems, you have held broken packages.

torsdag den 17. november 2022 skrev Vince ***@***.***>:

**Comment by Peter1511ogluigi** [comment]
Hi Vincent

I have just realized that I have somehow installed the wrong version of
Ubuntu (22.04 instead of 20.04) which explains why your procedure did not
work.
I have tried once again and now it works with the change in the
sources.list.
The part in installation on hystrath webpage where I type:

 sudo apt-get install g++-7 gcc-7

does still not work, so I would highly recommend that you update to
what you have explained to me with:

sudo gedit /etc/apt/sources.list

and adding the line
 deb http://dk.archive.ubuntu.com/ubuntu/ bionic main universe

followed by
sudo apt update
sudo apt-get install gcc-7 g++-7 -y

Thanks for the help :D

/Peter


Den tir. 22. nov. 2022 kl. 16.52 skrev Vince ***@***.***>:

**Comment by Peter1511ogluigi** [comment]
Hey Again

Just a quick question.
When I now follow the installation guide, I reach a problem at point 5.
At point 5, I have to change directory to $WM_PROJECT_DIR
which somehow is placed in $HOME.
Now, since I have placed the OpenFOAM version in the same location $HOME, I
cannot use the ./Allwmake command
I get the output
bash: ./Allwmake: No such file or directory

Have you faced this problem of having both the

$WM_PROJECT_DIR

and

$WM_PROJECT_USER_DIR

in wrong location?

/Peter


Den ons. 7. dec. 2022 kl. 13.20 skrev Peter Bæk ***@***.***>:
